INSERT INTO endereco (pais, cidade, estado, codigo_postal, regiao) VALUES 
('Estados Unidos', 'Henderson', 'Kentucky', '42420', 'Sul'),
('Estados Unidos', 'Los Angeles', 'California', '90036', 'Oeste'),
('Estados Unidos', 'Fort Lauderdale', 'Florida', '33311', 'Sul'),
('Estados Unidos', 'Los Angeles', 'California', '90032', 'Oeste'),
('Estados Unidos', 'Concord', 'North Carolina', '28027', 'Sul'),
('Estados Unidos', 'Seattle', 'Washington', '98103', 'Oeste'),
('Estados Unidos', 'Fort Worth', 'Texas', '76106', 'Central'),
('Estados Unidos', 'Madison', 'Wisconsin', '53711', 'Central'),
('Estados Unidos', 'West Jordan', 'Utah', '84084', 'Oeste'),
('Estados Unidos', 'San Francisco', 'California', '94109', 'Oeste'),
('Estados Unidos', 'Fremont', 'Nebraska', '68025', 'Central'),
('Estados Unidos', 'Philadelphia', 'Pennsylvania', '19140', 'Leste'),
('Estados Unidos', 'Orem', 'Utah', '84057', 'Oeste'),
('Estados Unidos', 'Los Angeles', 'California', '90049', 'Oeste'),
('Estados Unidos', 'Houston', 'Texas', '77095', 'Central'),
('Estados Unidos', 'Richardson', 'Texas', '75080', 'Central'),
('Estados Unidos', 'Houston', 'Texas', '77041', 'Central'),
('Estados Unidos', 'Naperville', 'Illinois', '60540', 'Central'),
('Estados Unidos', 'Melbourne', 'Florida', '32935', 'Sul'),
('Estados Unidos', 'Eagan', 'Minnesota', '55122', 'Central'),
('Estados Unidos', 'Westland', 'Michigan', '48185', 'Central'),
('Estados Unidos', 'Dover', 'Delaware', '19901', 'Leste'),
('Estados Unidos', 'New Albany', 'Indiana', '47150', 'Central'),
('Estados Unidos', 'New York City', 'New York', '10024', 'Leste'),
('Estados Unidos', 'Troy', 'New York', '12180', 'Leste'),
('Estados Unidos', 'Los Angeles', 'California', '90004', 'Oeste'),
('Estados Unidos', 'Chicago', 'Illinois', '60610', 'Central'),
('Estados Unidos', 'Gilbert', 'Arizona', '85234', 'Oeste'),
('Estados Unidos', 'Springfield', 'Virginia', '22153', 'Sul'),
('Estados Unidos', 'New York City', 'New York', '10009', 'Leste'),
('Estados Unidos', 'Jackson', 'Michigan', '49201', 'Central'),
('Estados Unidos', 'Memphis', 'Tennessee', '38109', 'Sul'),
('Estados Unidos', 'Houston', 'Texas', '77070', 'Central'),
('Estados Unidos', 'Decatur', 'Alabama', '35601', 'Sul'),
('Estados Unidos', 'San Francisco', 'California', '94122', 'Oeste'),
('Estados Unidos', 'Durham', 'North Carolina', '27707', 'Sul'),
('Estados Unidos', 'Chicago', 'Illinois', '60623', 'Central'),
('Estados Unidos', 'Columbia', 'South Carolina', '29203', 'Sul'),
('Estados Unidos', 'Rochester', 'Minnesota', '55901', 'Central'),
('Estados Unidos', 'Minneapolis', 'Minnesota', '55407', 'Central'),
('Estados Unidos', 'Portland', 'Oregon', '97206', 'Oeste'),
('Estados Unidos', 'Saint Paul', 'Minnesota', '55106', 'Central'),
('Estados Unidos', 'Aurora', 'Colorado', '80013', 'Oeste'),
('Estados Unidos', 'Charlotte', 'North Carolina', '28205', 'Sul'),
('Estados Unidos', 'Orland Park', 'Illinois', '60462', 'Central'),
('Estados Unidos', 'New York City', 'New York', '10035', 'Leste'),
('Estados Unidos', 'Urbandale', 'Iowa', '50322', 'Central'),
('Estados Unidos', 'Columbus', 'Ohio', '43229', 'Leste'),
('Estados Unidos', 'Bristol', 'Tennessee', '37620', 'Sul'),
('Estados Unidos', 'Wilmington', 'Delaware', '19805', 'Leste'),
('Estados Unidos', 'Bloomington', 'Illinois', '61701', 'Central'),
('Estados Unidos', 'Phoenix', 'Arizona', '85023', 'Oeste'),
('Estados Unidos', 'Roseville', 'California', '95661', 'Oeste'),
('Estados Unidos', 'Independence', 'Missouri', '64055', 'Central'),
('Estados Unidos', 'Pasadena', 'California', '91104', 'Oeste'),
('Estados Unidos', 'Newark', 'Ohio', '43055', 'Leste'),
('Estados Unidos', 'Franklin', 'Wisconsin', '53132', 'Central'),
('Estados Unidos', 'Scottsdale', 'Arizona', '85254', 'Oeste'),
('Estados Unidos', 'San Jose', 'California', '95123', 'Oeste'),
('Estados Unidos', 'Seattle', 'Washington', '98105', 'Oeste'),
('Estados Unidos', 'Seattle', 'Washington', '98115', 'Oeste'),
('Estados Unidos', 'Edmond', 'Oklahoma', '73034', 'Central'),
('Estados Unidos', 'Los Angeles', 'California', '90045', 'Oeste'),
('Estados Unidos', 'Philadelphia', 'Pennsylvania', '19134', 'Leste'),
('Estados Unidos', 'Carlsbad', 'New Mexico', '88220', 'Oeste'),
('Estados Unidos', 'San Antonio', 'Texas', '78207', 'Central'),
('Estados Unidos', 'Houston', 'Texas', '77036', 'Central'),
('Estados Unidos', 'Decatur', 'Illinois', '62521', 'Central'),
('Estados Unidos', 'Monroe', 'Louisiana', '71203', 'Sul'),
('Estados Unidos', 'Fairfield', 'Connecticut', '6824', 'Leste'),
('Estados Unidos', 'Grand Prairie', 'Texas', '75051', 'Central'),
('Estados Unidos', 'Redlands', 'California', '92374', 'Oeste'),
('Estados Unidos', 'Hamilton', 'Ohio', '45011', 'Leste'),
('Estados Unidos', 'Westfield', 'New Jersey', '7090', 'Leste'),
('Estados Unidos', 'Philadelphia', 'Pennsylvania', '19120', 'Leste'),
('Estados Unidos', 'Akron', 'Ohio', '44312', 'Leste'),
('Estados Unidos', 'Denver', 'Colorado', '80219', 'Oeste'),
('Estados Unidos', 'Dallas', 'Texas', '75220', 'Central'),
('Estados Unidos', 'Franklin', 'Tennessee', '37064', 'Sul'),
('Estados Unidos', 'Whittier', 'California', '90604', 'Oeste'),
('Estados Unidos', 'Saginaw', 'Michigan', '48601', 'Central'),
('Estados Unidos', 'Medina', 'Ohio', '44256', 'Leste'),
('Estados Unidos', 'Dublin', 'Ohio', '43017', 'Leste'),
('Estados Unidos', 'Detroit', 'Michigan', '48227', 'Central'),
('Estados Unidos', 'Columbia', 'Tennessee', '38401', 'Sul'),
('Estados Unidos', 'Tampa', 'Florida', '33614', 'Sul'),
('Estados Unidos', 'Santa Clara', 'California', '95051', 'Oeste'),
('Estados Unidos', 'Lakeville', 'Minnesota', '55044', 'Central'),
('Estados Unidos', 'San Diego', 'California', '92037', 'Oeste'),
('Estados Unidos', 'Pasadena', 'Texas', '77506', 'Central'),
('Estados Unidos', 'Brentwood', 'California', '94513', 'Oeste'),
('Estados Unidos', 'Chapel Hill', 'North Carolina', '27514', 'Sul'),
('Estados Unidos', 'Morristown', 'New Jersey', '7960', 'Leste'),
('Estados Unidos', 'Cincinnati', 'Ohio', '45231', 'Leste'),
('Estados Unidos', 'San Francisco', 'California', '94110', 'Oeste'),
('Estados Unidos', 'Inglewood', 'California', '90301', 'Oeste'),
('Estados Unidos', 'Tamarac', 'Florida', '33319', 'Sul'),
('Estados Unidos', 'Colorado Springs', 'Colorado', '80906', 'Oeste'),
('Estados Unidos', 'Belleville', 'New Jersey', '7109', 'Leste'),
('Estados Unidos', 'Taylor', 'Michigan', '48180', 'Central'),
('Estados Unidos', 'Lakewood', 'New Jersey', '8701', 'Leste'),
('Estados Unidos', 'Arlington', 'Virginia', '22204', 'Sul'),
('Estados Unidos', 'Arvada', 'Colorado', '80004', 'Oeste'),
('Estados Unidos', 'Hackensack', 'New Jersey', '7601', 'Leste'),
('Estados Unidos', 'Saint Petersburg', 'Florida', '33710', 'Sul'),
('Estados Unidos', 'Philadelphia', 'Pennsylvania', '19143', 'Leste'),
('Estados Unidos', 'Long Beach', 'California', '90805', 'Oeste'),
('Estados Unidos', 'Hesperia', 'California', '92345', 'Oeste'),
('Estados Unidos', 'Murfreesboro', 'Tennessee', '37130', 'Sul'),
('Estados Unidos', 'Layton', 'Utah', '84041', 'Oeste'),
('Estados Unidos', 'Austin', 'Texas', '78745', 'Central'),
('Estados Unidos', 'Lowell', 'Massachusetts', '1852', 'Leste'),
('Estados Unidos', 'Columbus', 'Georgia', '31907', 'Sul'),
('Estados Unidos', 'Manchester', 'Connecticut', '6040', 'Leste'),
('Estados Unidos', 'Harlingen', 'Texas', '78550', 'Central'),
('Estados Unidos', 'Tucson', 'Arizona', '85705', 'Oeste'),
('Estados Unidos', 'Quincy', 'Illinois', '62301', 'Central'),
('Estados Unidos', 'Franklin', 'Massachusetts', '2038', 'Leste'),
('Estados Unidos', 'Pembroke Pines', 'Florida', '33024', 'Sul'),
('Estados Unidos', 'Des Moines', 'Washington', '98198', 'Oeste'),
('Estados Unidos', 'Peoria', 'Illinois', '61604', 'Central'),
('Estados Unidos', 'Las Vegas', 'Nevada', '89115', 'Oeste'),
('Estados Unidos', 'Warwick', 'Rhode Island', '2886', 'Leste'),
('Estados Unidos', 'Miami', 'Florida', '33180', 'Sul'),
('Estados Unidos', 'Wilmington', 'North Carolina', '28403', 'Sul'),
('Estados Unidos', 'Huntington Beach', 'California', '92646', 'Oeste'),
('Estados Unidos', 'Richmond', 'Kentucky', '40475', 'Sul'),
('Estados Unidos', 'Louisville', 'Colorado', '80027', 'Oeste'),
('Estados Unidos', 'Lawrence', 'Massachusetts', '1841', 'Leste'),
('Estados Unidos', 'Jackson', 'Mississippi', '39212', 'Sul'),
('Estados Unidos', 'Canton', 'Michigan', '48187', 'Central'),
('Estados Unidos', 'New Rochelle', 'New York', '10801', 'Leste'),
('Estados Unidos', 'Gastonia', 'North Carolina', '28052', 'Sul'),
('Estados Unidos', 'Jacksonville', 'Florida', '32216', 'Sul'),
('Estados Unidos', 'Columbus', 'Indiana', '47201', 'Central'),
('Estados Unidos', 'Auburn', 'New York', '13021', 'Leste'),
('Estados Unidos', 'Norman', 'Oklahoma', '73071', 'Central'),
('Estados Unidos', 'Concord', 'California', '94521', 'Oeste'),
('Estados Unidos', 'Park Ridge', 'Illinois', '60068', 'Central'),
('Estados Unidos', 'Amarillo', 'Texas', '79109', 'Central'),
('Estados Unidos', 'Lindenhurst', 'New York', '11757', 'Leste'),
('Estados Unidos', 'Los Angeles', 'California', '90008', 'Oeste'),
('Estados Unidos', 'San Diego', 'California', '92024', 'Oeste'),
('Estados Unidos', 'Huntsville', 'Texas', '77340', 'Central'),
('Estados Unidos', 'Rochester', 'New York', '14609', 'Leste'),
('Estados Unidos', 'Fayetteville', 'Arkansas', '72701', 'Sul'),
('Estados Unidos', 'Costa Mesa', 'California', '92627', 'Oeste'),
('Estados Unidos', 'Parker', 'Colorado', '80134', 'Oeste'),
('Estados Unidos', 'Atlanta', 'Georgia', '30318', 'Sul'),
('Estados Unidos', 'Gladstone', 'Missouri', '64118', 'Central'),
('Estados Unidos', 'Great Falls', 'Montana', '59405', 'Oeste'),
('Estados Unidos', 'Detroit', 'Michigan', '48234', 'Central'),
('Estados Unidos', 'Lakeland', 'Florida', '33801', 'Sul'),
('Estados Unidos', 'Montgomery', 'Alabama', '36116', 'Sul'),
('Estados Unidos', 'Mesa', 'Arizona', '85204', 'Oeste'),
('Estados Unidos', 'Chicago', 'Illinois', '60653', 'Central'),
('Estados Unidos', 'Green Bay', 'Wisconsin', '54302', 'Central'),
('Estados Unidos', 'Springfield', 'Ohio', '45503', 'Leste'),
('Estados Unidos', 'Anaheim', 'California', '92804', 'Oeste'),
('Estados Unidos', 'Marysville', 'Washington', '98270', 'Oeste'),
('Estados Unidos', 'Salem', 'Oregon', '97301', 'Oeste'),
('Estados Unidos', 'Laredo', 'Texas', '78041', 'Central'),
('Estados Unidos', 'Dallas', 'Texas', '75217', 'Central'),
('Estados Unidos', 'Grove City', 'Ohio', '43123', 'Leste'),
('Estados Unidos', 'New York City', 'New York', '10011', 'Leste'),
('Estados Unidos', 'Dearborn', 'Michigan', '48126', 'Central'),
('Estados Unidos', 'Warner Robins', 'Georgia', '31088', 'Sul'),
('Estados Unidos', 'Vallejo', 'California', '94591', 'Oeste'),
('Estados Unidos', 'Mission Viejo', 'California', '92691', 'Oeste'),
('Estados Unidos', 'Rochester Hills', 'Michigan', '48307', 'Central'),
('Estados Unidos', 'Plainfield', 'New Jersey', '7060', 'Leste'),
('Estados Unidos', 'Sierra Vista', 'Arizona', '85635', 'Oeste'),
('Estados Unidos', 'Vancouver', 'Washington', '98661', 'Oeste'),
('Estados Unidos', 'Aurora', 'Illinois', '60505', 'Central'),
('Estados Unidos', 'Arlington', 'Texas', '76017', 'Central'),
('Estados Unidos', 'Louisville', 'Kentucky', '40214', 'Sul'),
('Estados Unidos', 'Dallas', 'Texas', '75081', 'Central'),
('Estados Unidos', 'Cleveland', 'Ohio', '44105', 'Leste'),
('Estados Unidos', 'Tyler', 'Texas', '75701', 'Central'),
('Estados Unidos', 'Burlington', 'North Carolina', '27217', 'Sul'),
('Estados Unidos', 'Waynesboro', 'Virginia', '22980', 'Sul'),
('Estados Unidos', 'Chester', 'Pennsylvania', '19013', 'Leste'),
('Estados Unidos', 'Cary', 'North Carolina', '27511', 'Sul'),
('Estados Unidos', 'Palm Coast', 'Florida', '32137', 'Sul'),
('Estados Unidos', 'Mount Vernon', 'New York', '10550', 'Leste'),
('Estados Unidos', 'Detroit', 'Michigan', '48205', 'Central'),
('Estados Unidos', 'Hialeah', 'Florida', '33012', 'Sul'),
('Estados Unidos', 'Oceanside', 'New York', '11572', 'Leste'),
('Estados Unidos', 'San Diego', 'California', '92105', 'Oeste'),
('Estados Unidos', 'Evanston', 'Illinois', '60201', 'Central'),
('Estados Unidos', 'Trenton', 'Michigan', '48183', 'Central'),
('Estados Unidos', 'Cottage Grove', 'Minnesota', '55016', 'Central'),
('Estados Unidos', 'Bossier City', 'Louisiana', '71111', 'Sul'),
('Estados Unidos', 'Des Moines', 'Iowa', '50315', 'Central'),
('Estados Unidos', 'Lancaster', 'California', '93534', 'Oeste'),
('Estados Unidos', 'Richmond', 'Virginia', '23223', 'Sul'),
('Estados Unidos', 'Asheville', 'North Carolina', '28806', 'Sul'),
('Estados Unidos', 'Lake Elsinore', 'California', '92530', 'Oeste'),
('Estados Unidos', 'Omaha', 'Nebraska', '68104', 'Central'),
('Estados Unidos', 'Edmonds', 'Washington', '98026', 'Oeste'),
('Estados Unidos', 'Santa Ana', 'California', '92704', 'Oeste'),
('Estados Unidos', 'Milwaukee', 'Wisconsin', '53209', 'Central'),
('Estados Unidos', 'Florence', 'Kentucky', '41042', 'Sul'),
('Estados Unidos', 'Lorain', 'Ohio', '44052', 'Leste'),
('Estados Unidos', 'Linden', 'New Jersey', '7036', 'Leste'),
('Estados Unidos', 'Salinas', 'California', '93905', 'Oeste'),
('Estados Unidos', 'New Brunswick', 'New Jersey', '8901', 'Leste'),
('Estados Unidos', 'Lancaster', 'Pennsylvania', '17602', 'Leste'),
('Estados Unidos', 'Concord', 'New Hampshire', '3301', 'Leste'),
('Estados Unidos', 'Columbia', 'Maryland', '21044', 'Leste'),
('Estados Unidos', 'Garland', 'Texas', '75043', 'Central'),
('Estados Unidos', 'Norwich', 'Connecticut', '6360', 'Leste'),
('Estados Unidos', 'Alexandria', 'Virginia', '22304', 'Sul'),
('Estados Unidos', 'Toledo', 'Ohio', '43615', 'Leste'),
('Estados Unidos', 'Farmington', 'New Mexico', '87401', 'Oeste'),
('Estados Unidos', 'Riverside', 'California', '92503', 'Oeste'),
('Estados Unidos', 'Torrance', 'California', '90503', 'Oeste'),
('Estados Unidos', 'Round Rock', 'Texas', '78664', 'Central'),
('Estados Unidos', 'Oceanside', 'California', '92054', 'Oeste'),
('Estados Unidos', 'Boca Raton', 'Florida', '33433', 'Sul'),
('Estados Unidos', 'Virginia Beach', 'Virginia', '23464', 'Sul'),
('Estados Unidos', 'Murrieta', 'California', '92563', 'Oeste'),
('Estados Unidos', 'Jacksonville', 'North Carolina', '28540', 'Sul'),
('Estados Unidos', 'Burlington', 'Iowa', '52601', 'Central'),
('Estados Unidos', 'Olympia', 'Washington', '98502', 'Oeste'),
('Estados Unidos', 'Washington', 'District of Columbia', '20016', 'Leste'),
('Estados Unidos', 'Jefferson City', 'Missouri', '65109', 'Central'),
('Estados Unidos', 'Saint Peters', 'Missouri', '63376', 'Central'),
('Estados Unidos', 'Rockford', 'Illinois', '61107', 'Central'),
('Estados Unidos', 'Miami', 'Florida', '33142', 'Sul'),
('Estados Unidos', 'Brownsville', 'Texas', '78521', 'Central'),
('Estados Unidos', 'Yonkers', 'New York', '10701', 'Leste'),
('Estados Unidos', 'Oakland', 'California', '94601', 'Oeste'),
('Estados Unidos', 'Monroe', 'North Carolina', '28110', 'Sul'),
('Estados Unidos', 'Clinton', 'Maryland', '20735', 'Leste'),
('Estados Unidos', 'Encinitas', 'California', '92024', 'Oeste'),
('Estados Unidos', 'Roswell', 'Georgia', '30076', 'Sul'),
('Estados Unidos', 'Jonesboro', 'Arkansas', '72401', 'Sul'),
('Estados Unidos', 'Richmond', 'Indiana', '47374', 'Central'),
('Estados Unidos', 'Antioch', 'California', '94509', 'Oeste'),
('Estados Unidos', 'Homestead', 'Florida', '33030', 'Sul'),
('Estados Unidos', 'La Porte', 'Indiana', '46350', 'Central'),
('Estados Unidos', 'Lansing', 'Michigan', '48911', 'Central'),
('Estados Unidos', 'Cuyahoga Falls', 'Ohio', '44221', 'Leste'),
('Estados Unidos', 'Reno', 'Nevada', '89502', 'Oeste'),
('Estados Unidos', 'Harrisonburg', 'Virginia', '22801', 'Sul'),
('Estados Unidos', 'Escondido', 'California', '92025', 'Oeste'),
('Estados Unidos', 'Royal Oak', 'Michigan', '48073', 'Central'),
('Estados Unidos', 'Rockville', 'Maryland', '20852', 'Leste'),
('Estados Unidos', 'Coral Springs', 'Florida', '33065', 'Sul'),
('Estados Unidos', 'Buffalo', 'New York', '14215', 'Leste'),
('Estados Unidos', 'Boynton Beach', 'Florida', '33437', 'Sul'),
('Estados Unidos', 'Gulfport', 'Mississippi', '39503', 'Sul'),
('Estados Unidos', 'Fresno', 'California', '93727', 'Oeste'),
('Estados Unidos', 'Greenville', 'North Carolina', '27834', 'Sul'),
('Estados Unidos', 'Long Beach', 'New York', '11561', 'Leste'),
('Estados Unidos', 'Florence', 'Alabama', '35630', 'Sul'),
('Estados Unidos', 'Macon', 'Georgia', '31204', 'Sul'),
('Estados Unidos', 'Cedar Rapids', 'Iowa', '52402', 'Central'),
('Estados Unidos', 'Providence', 'Rhode Island', '2908', 'Leste'),
('Estados Unidos', 'Pueblo', 'Colorado', '81001', 'Oeste'),
('Estados Unidos', 'Fairfield', 'California', '94533', 'Oeste'),
('Estados Unidos', 'Deltona', 'Florida', '32725', 'Sul'),
('Estados Unidos', 'Murray', 'Kentucky', '42071', 'Sul'),
('Estados Unidos', 'Middletown', 'Connecticut', '6457', 'Leste'),
('Estados Unidos', 'Freeport', 'New York', '11520', 'Leste'),
('Estados Unidos', 'Pico Rivera', 'California', '90660', 'Oeste'),
('Estados Unidos', 'Provo', 'Utah', '84604', 'Oeste'),
('Estados Unidos', 'Pleasant Grove', 'Utah', '84062', 'Oeste'),
('Estados Unidos', 'Smyrna', 'Georgia', '30080', 'Sul'),
('Estados Unidos', 'Salem', 'Virginia', '24153', 'Sul'),
('Estados Unidos', 'Parma', 'Ohio', '44134', 'Leste'),
('Estados Unidos', 'Mobile', 'Alabama', '36608', 'Sul'),
('Estados Unidos', 'New Bedford', 'Massachusetts', '2740', 'Leste'),
('Estados Unidos', 'Irving', 'Texas', '75061', 'Central'),
('Estados Unidos', 'Vineland', 'New Jersey', '8360', 'Leste'),
('Estados Unidos', 'Glendale', 'Arizona', '85301', 'Oeste'),
('Estados Unidos', 'Niagara Falls', 'New York', '14304', 'Leste'),
('Estados Unidos', 'Thomasville', 'North Carolina', '27360', 'Sul'),
('Estados Unidos', 'Westminster', 'California', '92683', 'Oeste'),
('Estados Unidos', 'Jackson', 'Tennessee', '38301', 'Sul'),
('Estados Unidos', 'Coppell', 'Texas', '75019', 'Central'),
('Estados Unidos', 'Pomona', 'California', '91767', 'Oeste'),
('Estados Unidos', 'North Las Vegas', 'Nevada', '89031', 'Oeste'),
('Estados Unidos', 'Allentown', 'Pennsylvania', '18103', 'Leste'),
('Estados Unidos', 'Newark', 'Delaware', '19711', 'Leste'),
('Estados Unidos', 'Tempe', 'Arizona', '85281', 'Oeste'),
('Estados Unidos', 'Laguna Niguel', 'California', '92677', 'Oeste'),
('Estados Unidos', 'Bridgeton', 'New Jersey', '8302', 'Leste'),
('Estados Unidos', 'Everett', 'Massachusetts', '2149', 'Leste'),
('Estados Unidos', 'Watertown', 'New York', '13601', 'Leste'),
('Estados Unidos', 'Appleton', 'Wisconsin', '54915', 'Central'),
('Estados Unidos', 'Bellevue', 'Washington', '98006', 'Oeste'),
('Estados Unidos', 'Allen', 'Texas', '75002', 'Central'),
('Estados Unidos', 'El Paso', 'Texas', '79907', 'Central'),
('Estados Unidos', 'Grapevine', 'Texas', '76051', 'Central'),
('Estados Unidos', 'Carrollton', 'Texas', '75007', 'Central'),
('Estados Unidos', 'Smyrna', 'Tennessee', '37167', 'Sul'),
('Estados Unidos', 'Kent', 'Washington', '98031', 'Oeste'),
('Estados Unidos', 'Lafayette', 'Louisiana', '70506', 'Sul'),
('Estados Unidos', 'Tigard', 'Oregon', '97224', 'Oeste'),
('Estados Unidos', 'Skokie', 'Illinois', '60076', 'Central'),
('Estados Unidos', 'Plano', 'Texas', '75023', 'Central'),
('Estados Unidos', 'Suffolk', 'Virginia', '23434', 'Sul'),
('Estados Unidos', 'Indianapolis', 'Indiana', '46203', 'Central'),
('Estados Unidos', 'Bayonne', 'New Jersey', '7002', 'Leste'),
('Estados Unidos', 'Fayetteville', 'North Carolina', '28314', 'Sul'),
('Estados Unidos', 'Greensboro', 'North Carolina', '27405', 'Sul'),
('Estados Unidos', 'Baltimore', 'Maryland', '21215', 'Leste'),
('Estados Unidos', 'Kenosha', 'Wisconsin', '53142', 'Central'),
('Estados Unidos', 'Olathe', 'Kansas', '66062', 'Central'),
('Estados Unidos', 'Auburn', 'Washington', '98002', 'Oeste'),
('Estados Unidos', 'Tulsa', 'Oklahoma', '74133', 'Central'),
('Estados Unidos', 'Redmond', 'Oregon', '97756', 'Oeste'),
('Estados Unidos', 'Raleigh', 'North Carolina', '27604', 'Sul'),
('Estados Unidos', 'Muskogee', 'Oklahoma', '74403', 'Central'),
('Estados Unidos', 'Meriden', 'Connecticut', '6450', 'Leste'),
('Estados Unidos', 'Bowling Green', 'Kentucky', '42104', 'Sul'),
('Estados Unidos', 'South Bend', 'Indiana', '46614', 'Central'),
('Estados Unidos', 'Bristol', 'Connecticut', '6010', 'Leste'),
('Estados Unidos', 'Henderson', 'Nevada', '89015', 'Oeste'),
('Estados Unidos', 'Spokane', 'Washington', '99207', 'Oeste'),
('Estados Unidos', 'Keller', 'Texas', '76248', 'Central'),
('Estados Unidos', 'Fairfield', 'Ohio', '45014', 'Leste'),
('Estados Unidos', 'Port Orange', 'Florida', '32127', 'Sul'),
('Estados Unidos', 'Medford', 'Oregon', '97504', 'Oeste'),
('Estados Unidos', 'Charlottesville', 'Virginia', '22901', 'Sul'),
('Estados Unidos', 'Missoula', 'Montana', '59801', 'Oeste'),
('Estados Unidos', 'Miami', 'Florida', '33178', 'Sul'),
('Estados Unidos', 'Florence', 'South Carolina', '29501', 'Sul'),
('Estados Unidos', 'Springfield', 'Oregon', '97477', 'Oeste'),
('Estados Unidos', 'Apopka', 'Florida', '32712', 'Sul'),
('Estados Unidos', 'Reading', 'Pennsylvania', '19601', 'Leste'),
('Estados Unidos', 'Broomfield', 'Colorado', '80020', 'Oeste'),
('Estados Unidos', 'Springfield', 'Missouri', '65807', 'Central'),
('Estados Unidos', 'Paterson', 'New Jersey', '7501', 'Leste'),
('Estados Unidos', 'Oklahoma City', 'Oklahoma', '73120', 'Central'),
('Estados Unidos', 'Chesapeake', 'Virginia', '23320', 'Sul'),
('Estados Unidos', 'Lubbock', 'Texas', '79424', 'Central'),
('Estados Unidos', 'Columbia', 'Missouri', '65203', 'Central'),
('Estados Unidos', 'Johnson City', 'Tennessee', '37604', 'Sul'),
('Estados Unidos', 'Auburn', 'Alabama', '36830', 'Sul'),
('Estados Unidos', 'San Bernardino', 'California', '92404', 'Oeste'),
('Estados Unidos', 'Leominster', 'Massachusetts', '1453', 'Leste'),
('Estados Unidos', 'Bozeman', 'Montana', '59715', 'Oeste'),
('Estados Unidos', 'Peoria', 'Arizona', '85345', 'Oeste'),
('Estados Unidos', 'Lakewood', 'Ohio', '44107', 'Leste'),
('Estados Unidos', 'Perth Amboy', 'New Jersey', '8861', 'Leste'),
('Estados Unidos', 'Ontario', 'California', '91761', 'Oeste'),
('Estados Unidos', 'Rancho Cucamonga', 'California', '91730', 'Oeste'),
('Estados Unidos', 'Moorhead', 'Minnesota', '56560', 'Central'),
('Estados Unidos', 'Mesquite', 'Texas', '75150', 'Central'),
('Estados Unidos', 'Stockton', 'California', '95207', 'Oeste'),
('Estados Unidos', 'Ormond Beach', 'Florida', '32174', 'Sul'),
('Estados Unidos', 'Sunnyvale', 'California', '94086', 'Oeste'),
('Estados Unidos', 'Dover', 'New Hampshire', '3820', 'Leste'),
('Estados Unidos', 'York', 'Pennsylvania', '17403', 'Leste'),
('Estados Unidos', 'College Station', 'Texas', '77840', 'Central'),
('Estados Unidos', 'Saint Louis', 'Missouri', '63116', 'Central'),
('Estados Unidos', 'Quincy', 'Massachusetts', '2169', 'Leste'),
('Estados Unidos', 'Manteca', 'California', '95336', 'Oeste'),
('Estados Unidos', 'Kent', 'Ohio', '44240', 'Leste'),
('Estados Unidos', 'San Angelo', 'Texas', '76903', 'Central'),
('Estados Unidos', 'Salt Lake City', 'Utah', '84106', 'Oeste'),
('Estados Unidos', 'Huntsville', 'Alabama', '35810', 'Sul'),
('Estados Unidos', 'Knoxville', 'Tennessee', '37918', 'Sul'),
('Estados Unidos', 'Little Rock', 'Arkansas', '72209', 'Sul'),
('Estados Unidos', 'Lincoln Park', 'Michigan', '48146', 'Central'),
('Estados Unidos', 'Marion', 'Ohio', '43302', 'Leste'),
('Estados Unidos', 'Littleton', 'Colorado', '80122', 'Oeste'),
('Estados Unidos', 'Bangor', 'Maine', '4401', 'Leste'),
('Estados Unidos', 'Southaven', 'Mississippi', '38671', 'Sul'),
('Estados Unidos', 'New Castle', 'Indiana', '47362', 'Central'),
('Estados Unidos', 'Midland', 'Michigan', '48640', 'Central'),
('Estados Unidos', 'Sioux Falls', 'South Dakota', '57103', 'Central'),
('Estados Unidos', 'Fort Collins', 'Colorado', '80525', 'Oeste'),
('Estados Unidos', 'Lafayette', 'Indiana', '47905', 'Central'),
('Estados Unidos', 'Clarksville', 'Tennessee', '37042', 'Sul'),
('Estados Unidos', 'Sacramento', 'California', '95823', 'Oeste'),
('Estados Unidos', 'Thousand Oaks', 'California', '91360', 'Oeste'),
('Estados Unidos', 'Malden', 'Massachusetts', '2148', 'Leste'),
('Estados Unidos', 'Holyoke', 'Massachusetts', '1040', 'Leste'),
('Estados Unidos', 'Albuquerque', 'New Mexico', '87105', 'Oeste'),
('Estados Unidos', 'Sparks', 'Nevada', '89431', 'Oeste'),
('Estados Unidos', 'Coachella', 'California', '92236', 'Oeste'),
('Estados Unidos', 'Elmhurst', 'Illinois', '60126', 'Central'),
('Estados Unidos', 'Passaic', 'New Jersey', '7055', 'Leste'),
('Estados Unidos', 'North Charleston', 'South Carolina', '29406', 'Sul'),
('Estados Unidos', 'Newport News', 'Virginia', '23602', 'Sul'),
('Estados Unidos', 'Jamestown', 'New York', '14701', 'Leste'),
('Estados Unidos', 'Mishawaka', 'Indiana', '46544', 'Central'),
('Estados Unidos', 'Bowling Green', 'Ohio', '43402', 'Leste'),
('Estados Unidos', 'La Quinta', 'California', '92253', 'Oeste'),
('Estados Unidos', 'Tallahassee', 'Florida', '32303', 'Sul'),
('Estados Unidos', 'Nashville', 'Tennessee', '37211', 'Sul'),
('Estados Unidos', 'Bellingham', 'Washington', '98226', 'Oeste'),
('Estados Unidos', 'Woodstock', 'Illinois', '60098', 'Central'),
('Estados Unidos', 'Haltom City', 'Texas', '76117', 'Central'),
('Estados Unidos', 'Wheeling', 'Illinois', '60090', 'Central'),
('Estados Unidos', 'Summerville', 'South Carolina', '29483', 'Sul'),
('Estados Unidos', 'Hot Springs', 'Arkansas', '71901', 'Sul'),
('Estados Unidos', 'Englewood', 'Colorado', '80112', 'Oeste'),
('Estados Unidos', 'Lancaster', 'Ohio', '43130', 'Leste'),
('Estados Unidos', 'Las Cruces', 'New Mexico', '88001', 'Oeste'),
('Estados Unidos', 'Hoover', 'Alabama', '35244', 'Sul'),
('Estados Unidos', 'Frisco', 'Texas', '75034', 'Central'),
('Estados Unidos', 'Vacaville', 'California', '95687', 'Oeste'),
('Estados Unidos', 'Murray', 'Utah', '84107', 'Oeste'),
('Estados Unidos', 'Waukesha', 'Wisconsin', '53186', 'Central'),
('Estados Unidos', 'Bakersfield', 'California', '93309', 'Oeste'),
('Estados Unidos', 'Pompano Beach', 'Florida', '33068', 'Sul'),
('Estados Unidos', 'Troy', 'Ohio', '45373', 'Leste'),
('Estados Unidos', 'Corpus Christi', 'Texas', '78415', 'Central'),
('Estados Unidos', 'Redondo Beach', 'California', '90278', 'Oeste'),
('Estados Unidos', 'Orlando', 'Florida', '32839', 'Sul'),
('Estados Unidos', 'Orange', 'New Jersey', '7050', 'Leste'),
('Estados Unidos', 'Lake Charles', 'Louisiana', '70601', 'Sul'),
('Estados Unidos', 'Highland Park', 'Illinois', '60035', 'Central'),
('Estados Unidos', 'Hempstead', 'New York', '11550', 'Leste'),
('Estados Unidos', 'Noblesville', 'Indiana', '46060', 'Central'),
('Estados Unidos', 'Apple Valley', 'Minnesota', '55124', 'Central'),
('Estados Unidos', 'Mount Pleasant', 'South Carolina', '29464', 'Sul'),
('Estados Unidos', 'Sterling Heights', 'Michigan', '48310', 'Central'),
('Estados Unidos', 'Eau Claire', 'Wisconsin', '54703', 'Central'),
('Estados Unidos', 'Pharr', 'Texas', '78577', 'Central'),
('Estados Unidos', 'Billings', 'Montana', '59102', 'Oeste'),
('Estados Unidos', 'Gresham', 'Oregon', '97030', 'Oeste'),
('Estados Unidos', 'Chattanooga', 'Tennessee', '37421', 'Sul'),
('Estados Unidos', 'Meridian', 'Idaho', '83642', 'Oeste'),
('Estados Unidos', 'Apple Valley', 'California', '92307', 'Oeste'),
('Estados Unidos', 'Bolingbrook', 'Illinois', '60440', 'Central'),
('Estados Unidos', 'Maple Grove', 'Minnesota', '55369', 'Central'),
('Estados Unidos', 'Woodland', 'California', '95695', 'Oeste'),
('Estados Unidos', 'Missouri City', 'Texas', '77489', 'Central'),
('Estados Unidos', 'Pearland', 'Texas', '77581', 'Central'),
('Estados Unidos', 'San Mateo', 'California', '94403', 'Oeste'),
('Estados Unidos', 'Grand Rapids', 'Michigan', '49505', 'Central'),
('Estados Unidos', 'Visalia', 'California', '93277', 'Oeste'),
('Estados Unidos', 'Overland Park', 'Kansas', '66212', 'Central'),
('Estados Unidos', 'Temecula', 'California', '92592', 'Oeste'),
('Estados Unidos', 'Yucaipa', 'California', '92399', 'Oeste'),
('Estados Unidos', 'Revere', 'Massachusetts', '2151', 'Leste'),
('Estados Unidos', 'Conroe', 'Texas', '77301', 'Central'),
('Estados Unidos', 'Tinley Park', 'Illinois', '60477', 'Central'),
('Estados Unidos', 'Dubuque', 'Iowa', '52001', 'Central'),
('Estados Unidos', 'Dearborn Heights', 'Michigan', '48127', 'Central'),
('Estados Unidos', 'Santa Fe', 'New Mexico', '87505', 'Oeste'),
('Estados Unidos', 'Hickory', 'North Carolina', '28601', 'Sul'),
('Estados Unidos', 'Carol Stream', 'Illinois', '60188', 'Central'),
('Estados Unidos', 'Saint Cloud', 'Minnesota', '56301', 'Central'),
('Estados Unidos', 'North Miami', 'Florida', '33161', 'Sul'),
('Estados Unidos', 'Lawrence', 'Indiana', '46226', 'Central'),
('Estados Unidos', 'Plantation', 'Florida', '33317', 'Sul'),
('Estados Unidos', 'Port Saint Lucie', 'Florida', '34952', 'Sul'),
('Estados Unidos', 'Rock Hill', 'South Carolina', '29730', 'Sul'),
('Estados Unidos', 'Odessa', 'Texas', '79762', 'Central'),
('Estados Unidos', 'West Allis', 'Wisconsin', '53214', 'Central'),
('Estados Unidos', 'Chula Vista', 'California', '91911', 'Oeste'),
('Estados Unidos', 'Manhattan', 'Kansas', '66502', 'Central'),
('Estados Unidos', 'Altoona', 'Pennsylvania', '16602', 'Leste'),
('Estados Unidos', 'Thornton', 'Colorado', '80229', 'Oeste'),
('Estados Unidos', 'Champaign', 'Illinois', '61821', 'Central'),
('Estados Unidos', 'Bloomington', 'Indiana', '47401', 'Central'),
('Estados Unidos', 'Texarkana', 'Arkansas', '71854', 'Sul'),
('Estados Unidos', 'Edinburg', 'Texas', '78539', 'Central'),
('Estados Unidos', 'Baytown', 'Texas', '77520', 'Central'),
('Estados Unidos', 'Greenwood', 'Indiana', '46142', 'Central'),
('Estados Unidos', 'Lakewood', 'California', '90712', 'Oeste'),
('Estados Unidos', 'Woonsocket', 'Rhode Island', '2895', 'Leste'),
('Estados Unidos', 'Superior', 'Wisconsin', '54880', 'Central'),
('Estados Unidos', 'Bedford', 'Texas', '76021', 'Central'),
('Estados Unidos', 'Covington', 'Washington', '98042', 'Oeste'),
('Estados Unidos', 'Broken Arrow', 'Oklahoma', '74012', 'Central'),
('Estados Unidos', 'Miramar', 'Florida', '33023', 'Sul'),
('Estados Unidos', 'Hollywood', 'Florida', '33021', 'Sul'),
('Estados Unidos', 'Deer Park', 'Texas', '77536', 'Central'),
('Estados Unidos', 'Wichita', 'Kansas', '67212', 'Central'),
('Estados Unidos', 'Mcallen', 'Texas', '78501', 'Central'),
('Estados Unidos', 'Iowa City', 'Iowa', '52240', 'Central'),
('Estados Unidos', 'Boise', 'Idaho', '83704', 'Oeste'),
('Estados Unidos', 'Cranston', 'Rhode Island', '2920', 'Leste'),
('Estados Unidos', 'Freeport', 'Illinois', '61032', 'Central'),
('Estados Unidos', 'Port Arthur', 'Texas', '77642', 'Central'),
('Estados Unidos', 'Citrus Heights', 'California', '95610', 'Oeste'),
('Estados Unidos', 'The Colony', 'Texas', '75056', 'Central'),
('Estados Unidos', 'Redmond', 'Washington', '98052', 'Oeste'),
('Estados Unidos', 'Daytona Beach', 'Florida', '32114', 'Sul'),
('Estados Unidos', 'Bullhead City', 'Arizona', '86442', 'Oeste'),
('Estados Unidos', 'Portage', 'Indiana', '46368', 'Central'),
('Estados Unidos', 'Fargo', 'North Dakota', '58103', 'Central'),
('Estados Unidos', 'Elkhart', 'Indiana', '46514', 'Central'),
('Estados Unidos', 'San Gabriel', 'California', '91776', 'Oeste'),
('Estados Unidos', 'Margate', 'Florida', '33063', 'Sul'),
('Estados Unidos', 'Sandy Springs', 'Georgia', '30328', 'Sul'),
('Estados Unidos', 'Mentor', 'Ohio', '44060', 'Leste'),
('Estados Unidos', 'Lawton', 'Oklahoma', '73505', 'Central'),
('Estados Unidos', 'Hampton', 'Virginia', '23666', 'Sul'),
('Estados Unidos', 'Rome', 'New York', '13440', 'Leste'),
('Estados Unidos', 'La Crosse', 'Wisconsin', '54601', 'Central'),
('Estados Unidos', 'Lewiston', 'Idaho', '83501', 'Oeste'),
('Estados Unidos', 'Hattiesburg', 'Mississippi', '39401', 'Sul'),
('Estados Unidos', 'Danville', 'California', '94526', 'Oeste'),
('Estados Unidos', 'Mount Pleasant', 'Michigan', '48858', 'Central'),
('Estados Unidos', 'Logan', 'Utah', '84321', 'Oeste'),
('Estados Unidos', 'Waterbury', 'Connecticut', '6708', 'Leste'),
('Estados Unidos', 'Athens', 'Georgia', '30605', 'Sul'),
('Estados Unidos', 'Lewiston', 'Maine', '4240', 'Leste'),
('Estados Unidos', 'Danville', 'Illinois', '61832', 'Central'),
('Estados Unidos', 'Avondale', 'Arizona', '85323', 'Oeste'),
('Estados Unidos', 'Marietta', 'Georgia', '30062', 'Sul'),
('Estados Unidos', 'Yuma', 'Arizona', '85364', 'Oeste'),
('Estados Unidos', 'Wausau', 'Wisconsin', '54401', 'Central'),
('Estados Unidos', 'Pasco', 'Washington', '99301', 'Oeste'),
('Estados Unidos', 'Oak Park', 'Illinois', '60302', 'Central'),
('Estados Unidos', 'Pensacola', 'Florida', '32503', 'Sul'),
('Estados Unidos', 'League City', 'Texas', '77573', 'Central'),
('Estados Unidos', 'Gaithersburg', 'Maryland', '20877', 'Leste'),
('Estados Unidos', 'Lehi', 'Utah', '84043', 'Oeste'),
('Estados Unidos', 'Tuscaloosa', 'Alabama', '35401', 'Sul'),
('Estados Unidos', 'Moreno Valley', 'California', '92553', 'Oeste'),
('Estados Unidos', 'Georgetown', 'Kentucky', '40324', 'Sul'),
('Estados Unidos', 'Loveland', 'Colorado', '80538', 'Oeste'),
('Estados Unidos', 'Chandler', 'Arizona', '85224', 'Oeste'),
('Estados Unidos', 'Helena', 'Montana', '59601', 'Oeste'),
('Estados Unidos', 'Kirkwood', 'Missouri', '63122', 'Central'),
('Estados Unidos', 'Waco', 'Texas', '76706', 'Central'),
('Estados Unidos', 'Roseville', 'Michigan', '48066', 'Central'),
('Estados Unidos', 'Frankfort', 'Illinois', '60423', 'Central'),
('Estados Unidos', 'Bethlehem', 'Pennsylvania', '18018', 'Leste'),
('Estados Unidos', 'Roseville', 'Minnesota', '55113', 'Central'),
('Estados Unidos', 'Grand Island', 'Nebraska', '68801', 'Central'),
('Estados Unidos', 'Woodbury', 'Minnesota', '55125', 'Central'),
('Estados Unidos', 'Oak Park', 'Michigan', '48237', 'Central'),
('Estados Unidos', 'Rogers', 'Arkansas', '72756', 'Sul'),
('Estados Unidos', 'Clovis', 'New Mexico', '88101', 'Oeste'),
('Estados Unidos', 'Jupiter', 'Florida', '33458', 'Sul'),
('Estados Unidos', 'Santa Barbara', 'California', '93101', 'Oeste'),
('Estados Unidos', 'Cedar Hill', 'Texas', '75104', 'Central'),
('Estados Unidos', 'Norfolk', 'Nebraska', '68701', 'Central'),
('Estados Unidos', 'Draper', 'Utah', '84020', 'Oeste'),
('Estados Unidos', 'Ann Arbor', 'Michigan', '48104', 'Central'),
('Estados Unidos', 'La Mesa', 'California', '91941', 'Oeste'),
('Estados Unidos', 'Pocatello', 'Idaho', '83201', 'Oeste'),
('Estados Unidos', 'Holland', 'Michigan', '49423', 'Central'),
('Estados Unidos', 'Milford', 'Connecticut', '6460', 'Leste'),
('Estados Unidos', 'Buffalo Grove', 'Illinois', '60089', 'Central'),
('Estados Unidos', 'Lake Forest', 'California', '92630', 'Oeste'),
('Estados Unidos', 'Redding', 'California', '96003', 'Oeste'),
('Estados Unidos', 'Chico', 'California', '95928', 'Oeste'),
('Estados Unidos', 'Utica', 'New York', '13501', 'Leste'),
('Estados Unidos', 'Conway', 'Arkansas', '72032', 'Sul'),
('Estados Unidos', 'Cheyenne', 'Wyoming', '82001', 'Oeste'),
('Estados Unidos', 'Owensboro', 'Kentucky', '42301', 'Sul'),
('Estados Unidos', 'Caldwell', 'Idaho', '83605', 'Oeste'),
('Estados Unidos', 'Kenner', 'Louisiana', '70065', 'Sul'),
('Estados Unidos', 'Nashua', 'New Hampshire', '3060', 'Leste'),
('Estados Unidos', 'Bartlett', 'Tennessee', '38134', 'Sul'),
('Estados Unidos', 'Redwood City', 'California', '94061', 'Oeste'),
('Estados Unidos', 'Lebanon', 'Tennessee', '37087', 'Sul'),
('Estados Unidos', 'Santa Maria', 'California', '93454', 'Oeste'),
('Estados Unidos', 'Des Plaines', 'Illinois', '60016', 'Central'),
('Estados Unidos', 'Longview', 'Washington', '98632', 'Oeste'),
('Estados Unidos', 'Hendersonville', 'Tennessee', '37075', 'Sul'),
('Estados Unidos', 'Waterloo', 'Iowa', '50701', 'Central'),
('Estados Unidos', 'Cambridge', 'Massachusetts', '2138', 'Leste'),
('Estados Unidos', 'Palatine', 'Illinois', '60067', 'Central'),
('Estados Unidos', 'Beverly', 'Massachusetts', '1915', 'Leste'),
('Estados Unidos', 'Eugene', 'Oregon', '97405', 'Oeste'),
('Estados Unidos', 'Oxnard', 'California', '93030', 'Oeste'),
('Estados Unidos', 'Renton', 'Washington', '98059', 'Oeste'),
('Estados Unidos', 'Glenview', 'Illinois', '60025', 'Central'),
('Estados Unidos', 'Delray Beach', 'Florida', '33445', 'Sul'),
('Estados Unidos', 'Commerce City', 'Colorado', '80022', 'Oeste'),
('Estados Unidos', 'Texas City', 'Texas', '77590', 'Central'),
('Estados Unidos', 'Wilson', 'North Carolina', '27893', 'Sul'),
('Estados Unidos', 'Rio Rancho', 'New Mexico', '87124', 'Oeste'),
('Estados Unidos', 'Goldsboro', 'North Carolina', '27534', 'Sul'),
('Estados Unidos', 'Everett', 'Washington', '98208', 'Oeste'),
('Estados Unidos', 'Montebello', 'California', '90640', 'Oeste'),
('Estados Unidos', 'El Cajon', 'California', '92020', 'Oeste'),
('Estados Unidos', 'Beaumont', 'Texas', '77705', 'Central'),
('Estados Unidos', 'West Palm Beach', 'Florida', '33407', 'Sul'),
('Estados Unidos', 'Abilene', 'Texas', '79605', 'Central'),
('Estados Unidos', 'Normal', 'Illinois', '61761', 'Central'),
('Estados Unidos', 'Saint Charles', 'Missouri', '63301', 'Central'),
('Estados Unidos', 'Saint Charles', 'Illinois', '60174', 'Central'),
('Estados Unidos', 'Camarillo', 'California', '93010', 'Oeste'),
('Estados Unidos', 'Hillsboro', 'Oregon', '97123', 'Oeste'),
('Estados Unidos', 'Burbank', 'California', '91505', 'Oeste'),
('Estados Unidos', 'Modesto', 'California', '95351', 'Oeste'),
('Estados Unidos', 'Garden City', 'Kansas', '67846', 'Central'),
('Estados Unidos', 'Atlantic City', 'New Jersey', '8401', 'Leste'),
('Estados Unidos', 'Longmont', 'Colorado', '80501', 'Oeste'),
('Estados Unidos', 'Davis', 'California', '95616', 'Oeste'),
('Estados Unidos', 'Wheeling', 'West Virginia', '26003', 'Leste'),
('Estados Unidos', 'Morgan Hill', 'California', '95037', 'Oeste'),
('Estados Unidos', 'Clifton', 'New Jersey', '7011', 'Leste'),
('Estados Unidos', 'Sheboygan', 'Wisconsin', '53081', 'Central'),
('Estados Unidos', 'East Point', 'Georgia', '30344', 'Sul'),
('Estados Unidos', 'Rapid City', 'South Dakota', '57701', 'Central'),
('Estados Unidos', 'Andover', 'Massachusetts', '1810', 'Leste'),
('Estados Unidos', 'Kissimmee', 'Florida', '34741', 'Sul'),
('Estados Unidos', 'Shelton', 'Connecticut', '6484', 'Leste'),
('Estados Unidos', 'Danbury', 'Connecticut', '6810', 'Leste'),
('Estados Unidos', 'Marion', 'Iowa', '52302', 'Central'),
('Estados Unidos', 'Sanford', 'Florida', '32771', 'Sul'),
('Estados Unidos', 'San Marcos', 'Texas', '78666', 'Central'),
('Estados Unidos', 'Greeley', 'Colorado', '80634', 'Oeste'),
('Estados Unidos', 'Mansfield', 'Texas', '76063', 'Central'),
('Estados Unidos', 'Elyria', 'Ohio', '44035', 'Leste'),
('Estados Unidos', 'Twin Falls', 'Idaho', '83301', 'Oeste'),
('Estados Unidos', 'Coral Gables', 'Florida', '33134', 'Sul'),
('Estados Unidos', 'Romeoville', 'Illinois', '60441', 'Central'),
('Estados Unidos', 'Marlborough', 'Massachusetts', '1752', 'Leste'),
('Estados Unidos', 'Laurel', 'Maryland', '20707', 'Leste'),
('Estados Unidos', 'Bryan', 'Texas', '77803', 'Central'),
('Estados Unidos', 'Pine Bluff', 'Arkansas', '71603', 'Sul'),
('Estados Unidos', 'Aberdeen', 'South Dakota', '57401', 'Central'),
('Estados Unidos', 'Hagerstown', 'Maryland', '21740', 'Leste'),
('Estados Unidos', 'East Orange', 'New Jersey', '7017', 'Leste'),
('Estados Unidos', 'Arlington Heights', 'Illinois', '60004', 'Central'),
('Estados Unidos', 'Oswego', 'Illinois', '60543', 'Central'),
('Estados Unidos', 'Coon Rapids', 'Minnesota', '55433', 'Central'),
('Estados Unidos', 'San Clemente', 'California', '92672', 'Oeste'),
('Estados Unidos', 'Dublin', 'California', '94568', 'Oeste'),
('Estados Unidos', 'San Luis Obispo', 'California', '93405', 'Oeste'),
('Estados Unidos', 'Springdale', 'Arkansas', '72762', 'Sul'),
