INSERT INTO produto (nome, id_subcategoria) VALUES 
('Bush Somerset Collection Bookcase', 1),
('Hon Deluxe Fabric Upholstered Stacking Chairs, Rounded Back', 2),
('Self-Adhesive Address Labels for Typewriters by Universal', 3),
('Bretford CR4500 Series Slim Rectangular Table', 4),
('Eldon Fold N Roll Cart System', 5),
('Eldon Expressions Wood and Plastic Desk Accessories, Cherry Wood', 6),
('Newell 322', 7),
('Mitel 5320 IP Phone VoIP phone', 8),
('DXL Angle-View Binders with Locking Rings by Samsill', 9),
('Belkin F5C206VTEL 6 Outlet Surge', 10),
('Chromcraft Rectangular Conference Tables', 4),
('Konftel 250 Conference phone - Charcoal black', 8),
('Xerox 1967', 11),
('Fellowes PB200 Plastic Comb Binding Machine', 9),
('Holmes Replacement Filter for HEPA Air Cleaner, Very Large Room, HEPA Filter', 10),
('Storex DuraTech Recycled Plastic Frosted Binders', 9),
('Stur-D-Stor Shelving, Vertical 5-Shelf: 72"H x 36"W x 18 1/2"D', 5),
('Fellowes Super Stor/Drawer', 5),
('Newell 341', 7),
('Cisco SPA 501G IP Phone', 8),
('Wilson Jones Hanging View Binder, White, 1"', 9),
('Newell 318', 7),
('Acco Six-Outlet Power Strip, 4 Cord Length', 10),
('Global Deluxe Stacking Chair, Gray', 2),
('Wilson Jones Active Use Binders', 9),
('Imation 8GB Mini TravelDrive USB 2.0 Flash Drive', 12),
('Riverside Palais Royal Lawyers Bookcase, Royale Cherry Finish', 1),
('Avery Recycled Flexi-View Covers for Binding Systems', 9),
('Howard Miller 13-3/4" Diameter Brushed Chrome Round Wall Clock', 6),
('Poly String Tie Envelopes', 13),
('BOSTON Model 1800 Electric Pencil Sharpeners, Putty/Woodgrain', 7),
('Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Executive Red', 9),
('Lumber Crayons', 7),
('Easy-staple paper', 11),
('GE 30524EE4', 8),
('Electrix Architects Clamp-On Swing Arm Lamp, Black', 6),
('#10-4 1/8" x 9 1/2" Premium Diagonal Seam Envelopes', 13),
('Atlantic Metals Mobile 3-Shelf Bookcases, Custom Colors', 1),
('Global Fabric Managers Chair, Dark Gray', 2),
('Plantronics HL10 Handset Lifter', 8),
('Panasonic Kx-TS550', 8),
('Eldon Base for stackable storage shelf, platinum', 5),
('Advantus 10-Drawer Portable Organizer, Chrome Metal Frame, Smoke Drawers', 5),
('Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 25/Pack', 12),
('Wilson Jones Leather-Like Binders with DublLock Round Rings', 9),
('Gould Plastics 9-Pocket Panel Bin, 18-3/8w x 5-1/4d x 20-1/2h, Black', 5),
('Imation 8gb Micro Traveldrive Usb 2.0 Flash Drive', 12),
('LF Elite 3D Dazzle Designer Hard Case Cover, Lf Stylus Pen and Wiper For Apple Iphone 5c Mini Lite', 8),
('C-Line Peel & Stick Add-On Filing Pockets, 8-3/4 x 5-1/8, 10/Pack', 9),
('Avery 485', 3),
('Longer-Life Soft White Bulbs', 6),
('Global Leather Task Chair, Black', 2),
('Advantus Push Pins', 14),
('AT&T CL83451 4-Handset Telephone', 8),
('Home/Office Personal File Carts', 5),
('Xerox 232', 11),
('Novimex Turbo Task Chair', 2),
('Array Parchment Paper, Assorted Colors', 11),
('Plastic Binding Combs', 9),
('Prang Dustless Chalk Sticks', 7),
('Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 3/Pack', 12),
('Acco PRESSTEX Data Binder with Storage Hooks, Dark Blue, 14 7/8" X 11"', 9),
('Xerox 1943', 11),
('Luxo Economy Swing Arm Lamp', 6),
('Global Value Mid-Back Managers Chair, Gray', 2),
('Hunt BOSTON Model 1606 High-Volume Electric Pencil Sharpener, Beige', 7),
('netTALK DUO VoIP Telephone Service', 8),
('Snap-A-Way Black Print Carbonless Ruled Speed Letter, Triplicate', 11),
('Avery Binding System Hidden Tab Executive Style Index Sets', 9),
('Telephone Message Books with Fax/Mobile Section, 5 1/2" x 3 3/16"', 11),
('High-Back Leather Managers Chair', 2),
('Tenex Traditional Chairmats for Medium Pile Carpet, Standard Lip, 36" x 48"', 6),
('Safco Industrial Wire Shelving System', 5),
('Economy Binders', 9),
('6" Cubicle Wall Clock, Black', 6),
('SimpliFile Personal File, Black Granite, 15w x 6-15/16d x 11-1/4h', 5),
('Eldon Expressions Desk Accessory, Wood Pencil Holder, Oak', 6),
('1.7 Cubic Foot Compact "Cube" Office Refrigerators', 10),
('Avery Heavy-Duty EZD  Binder With Locking Rings', 9),
('Premium Writing Pencils, Soft, #2 by Central Association for the Blind', 7),
('Sortfiler Multipurpose Personal File Organizer, Black', 5),
('Jet-Pak Recycled Peel N Seal Padded Mailers', 13),
('Safco Industrial Wire Shelving', 5),
('Novimex Swivel Fabric Task Chair', 2),
('Logitech LS21 Speaker System - PC Multimedia - 2.1-CH - Wired', 12),
('Avery 511', 3),
('Eldon Portable Mobile Manager', 5),
('Turquoise Lead Holder with Pocket Clip', 7),
('Xerox 1995', 11),
('Xerox 1999', 11),
('Seth Thomas 13 1/2" Wall Clock', 6),
('Ibico Standard Transparent Covers', 9),
('Flexible Leather- Look Classic Collection Ring Binder', 9),
('9-3/4 Diameter Round Wall Clock', 6),
('Trimflex Flexible Post Binders', 9),
('Fellowes Basic Home/Office Series Surge Protectors', 10),
('Avery Personal Creations Heavyweight Cards', 11),
('SanDisk Ultra 64 GB MicroSDHC Class 10 Memory Card', 12),
('Avery Hidden Tab Dividers for Binding Systems', 9),
('Universal Premium White Copier/Laser Paper (20Lb. and 87 Bright)', 11),
('Logitech K350 2.4Ghz Wireless Keyboard', 12),
('Deflect-o DuraMat Lighweight, Studded, Beveled Mat for Low Pile Carpeting', 6),
('Avery Trapezoid Ring Binder, 3" Capacity, Black, 1040 sheets', 9),
('Memorex Mini Travel Drive 8 GB USB 2.0 Flash Drive', 12),
('Speck Products Candyshell Flip Case', 8),
('Newell Chalk Holder', 7),
('Logitech Gaming G510s - Keyboard', 12),
('Magnifier Swing Arm Lamp', 6),
('Hunt PowerHouse Electric Pencil Sharpener, Blue', 7),
('Avery Durable Plastic 1" Binders', 9),
('OIC Colored Binder Clips, Assorted Sizes', 14),
('Redi-Strip #10 Envelopes, 4 1/8 x 9 1/2', 13),
('Xerox 1921', 11),
('Tyvek  Top-Opening Peel & Seel Envelopes, Plain White', 13),
('Hon Racetrack Conference Tables', 4),
('GBC DocuBind 300 Electric Binding Machine', 9),
('Artistic Insta-Plaque', 6),
('Companion Letter/Legal File, Black', 5),
('Globe Weis Peel & Seel First Class Envelopes', 13),
('KLD Oscar II Style Snap-on Ultra Thin Side Flip Synthetic Leather Cover Case for HTC One HTC M7', 8),
('Global Deluxe High-Back Managers Chair', 2),
('Bevis 44 x 96 Conference Tables', 4),
('Avery Durable Slant Ring Binders, No Labels', 9),
('Trav-L-File Heavy-Duty Shuttle II, Black', 5),
('Global Task Chair, Black', 2),
('Eldon Cleatmat Plus Chair Mats for High Pile Carpets', 6),
('Anker 36W 4-Port USB Wall Charger Travel Power Adapter for iPhone 5s 5c 5', 8),
('Xerox 1916', 11),
('Staples', 14),
('Xerox 195', 11),
('Xerox 1880', 11),
('Sanford Colorific Colored Pencils, 12/Box', 7),
('Ideal Clamps', 14),
('GBC Wire Binding Strips', 9),
('Fiskars Softgrip Scissors', 15),
('Newell 343', 7),
('Convenience Packs of Business Envelopes', 13),
('Xerox 1911', 11),
('Sanyo 2.5 Cubic Foot Mid-Size Office Refrigerators', 10),
('Seth Thomas 14" Putty-Colored Wall Clock', 6),
('Plantronics Cordless Phone Headset with In-line Volume - M214C', 8),
('Anker Astro 15000mAh USB Portable Charger', 8),
('GBC Prestige Therm-A-Bind Covers', 9),
('Belkin 7 Outlet SurgeMaster Surge Protector with Phone Protection', 10),
('Jabra BIZ 2300 Duo QD Duo Corded Headset', 8),
('Southworth 25% Cotton Antique Laid Paper & Envelopes', 11),
('Xerox 1883', 11),
('Tenex Personal Project File with Scoop Front Design, Black', 5),
('Newell 311', 7),
('Avery 519', 3),
('Avaya 5420 Digital phone', 8),
('Xerox 1920', 11),
('Lenovo 17-Key USB Numeric Keypad', 12),
('Staple envelope', 13),
('Wilson Jones International Size A4 Ring Binders', 9),
('BIC Brite Liner Highlighters', 7),
('Lexmark MX611dhe Monochrome Laser Printer', 16),
('Space Solutions HD Industrial Steel Shelving.', 5),
('SAFCO Arco Folding Chair', 2),
('Sanford Liquid Accent Highlighters', 7),
('Kensington 7 Outlet MasterPiece Power Center', 10),
('JBL Micro Wireless Portable Bluetooth Speaker', 8),
('Adams Phone Message Book, Professional, 400 Message Capacity, 5 3/6” x 11”', 11),
('Xerox 1913', 11),
('Global Value Steno Chair, Gray', 2),
('Kensington 7 Outlet MasterPiece HOMEOFFICE Power Control Center', 10),
('Avery 51', 3),
('Acco 7-Outlet Masterpiece Power Center, Wihtout Fax/Phone Line Protection', 10),
('Padded Folding Chairs, Black, 4/Carton', 2),
('Acme Rosewood Handle Letter Opener', 15),
('Sanford Colorific Eraseable Coloring Pencils, 12 Count', 7),
('Tenex File Box, Personal Filing Tote with Lid, Black', 5),
('Imation Secure+ Hardware Encrypted USB 2.0 Flash Drive; 16GB', 12),
('AT&T TR1909W', 8),
('Nokia Lumia 521 (T-Mobile)', 8),
('HP Standard 104 key PS/2 Keyboard', 12),
('Avery Poly Binder Pockets', 9),
('SanDisk Ultra 32 GB MicroSDHC Class 10 Memory Card', 12),
('Personal Filing Tote with Lid, Black/Gray', 5),
('Atlantic Metals Mobile 4-Shelf Bookcases, Custom Colors', 1),
('I Needs 3d Hello Kitty Hybrid Silicone Case Cover for HTC One X 4g with 3d Hello Kitty Stylus Pen Green/pink', 8),
('Xerox 205', 11),
('4009 Highlighters by Sanford', 7),
('Binney & Smith Crayola Metallic Colored Pencils, 8-Color Set', 7),
('Binney & Smith inkTank Erasable Desk Highlighter, Chisel Tip, Yellow, 12/Box', 7),
('Decoflex Hanging Personal Folder File', 5),
('Pressboard Covers with Storage Hooks, 9 1/2" x 11", Light Blue', 9),
('Wirebound Message Books, 5-1/2 x 4 Forms, 2 or 4 Forms per Page', 11),
('Southworth 25% Cotton Linen-Finish Paper & Envelopes', 11),
('BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables', 4),
('Bravo II Megaboss 12-Amp Hard Body Upright, Replacement Belts, 2 Belts per Pack', 10),
('Eureka Sanitaire  Commercial Upright', 10),
('Eldon 200 Class Desk Accessories, Burgundy', 6),
('Nortel Business Series Terminal T7208 Digital phone', 8),
('Tennsco Lockers, Gray', 5),
('Panasonic KX-TG6844B Expandable Digital Cordless Telephone', 8),
('Advantus Push Pins, Aluminum Head', 14),
('Gould Plastics 18-Pocket Panel Bin, 34w x 5-1/4d x 20-1/2h', 5),
('Memorex Micro Travel Drive 8 GB', 12),
('Avery 505', 3),
('OSullivan 2-Door Barrister Bookcase in Odessa Pine', 1),
('Cisco 9971 IP Video Phone Charcoal', 16),
('Sony Micro Vault Click 16 GB USB 2.0 Flash Drive', 12),
('Adtran 1202752G1', 8),
('OIC Bulk Pack Metal Binder Clips', 14),
('While You Were Out Pads, 50 per Pad, 4 x 5 1/4, Green Cycle', 11),
('Executive Impressions 14" Two-Color Numerals Wall Clock', 6),
('Swingline SM12-08 MicroCut Jam Free Shredder', 16),
('Stanley Bostitch Contemporary Electric Pencil Sharpeners', 7),
('Sanford Uni-Blazer View Highlighters, Chisel Tip, Yellow', 7),
('Bevis 36 x 72 Conference Tables', 4),
('Rogers Deluxe File Chest', 5),
('Global Low Back Tilter Chair', 2),
('Global Push Button Managers Chair, Indigo', 2),
('GBC Instant Index System for Binding Systems', 9),
('Bush Advantage Collection Round Conference Table', 4),
('Bretford Rectangular Conference Table Tops', 4),
('Tenex Contemporary Contur Chairmats for Low and Medium Pile Carpet, Computer, 39" x 49"', 6),
('Logitech P710e Mobile Speakerphone', 12),
('Xerox 4200 Series MultiUse Premium Copy Paper (20Lb. and 84 Bright)', 11),
('Xerox 1957', 11),
('Luxo Professional Fluorescent Magnifier Lamp with Clamp-Mount Base', 6),
('Staple-based wall hangings', 6),
('PureGear Roll-On Screen Protector', 8),
('KI Conference Tables', 4),
('Eldon 100 Class Desk Accessories', 6),
('Safco Steel Mobile File Cart', 5),
('Adams Telephone Message Book w/Frequently-Called Numbers Space, 400 Messages per Book', 11),
('Honeywell Enviracaire Portable HEPA Air Cleaner for 17 x 22 Room', 10),
('Global Leather Highback Executive Chair with Pneumatic Height Adjustment, Black', 2),
('Wirebound Message Books, Two 4 1/4" x 5" Forms per Page', 11),
('Fellowes Personal Hanging Folder Files, Navy', 5),
('Tyvek Side-Opening Peel & Seel Expanding Envelopes', 13),
('Belkin 19" Vented Equipment Shelf, Black', 5),
('Logitech Mobile Speakerphone P710e - speaker phone', 8),
('Sabrent 4-Port USB 2.0 Hub', 12),
('Safco Industrial Shelving', 5),
('Acco 3-Hole Punch', 9),
('Eureka Disposable Bags for Sanitaire Vibra Groomer I Upright Vac', 10),
('Xerox WorkCentre 6505DN Laser Multifunction Printer', 16),
('Cisco Small Business SPA 502G VoIP phone', 8),
('Microsoft Sculpt Comfort Mouse', 12),
('Quartet Omega Colored Chalk, 12/Pack', 7),
('Bagged Rubber Bands', 14),
('Safco Commercial Shelving', 5),
('Recycled Interoffice Envelopes with String and Button Closure, 10 x 13', 13),
('Adjustable Depth Letter/Legal Cart', 5),
('Logitech 910-002974 M325 Wireless Mouse for Web Scrolling', 12),
('Regeneration Desk Collection', 6),
('Presstex Flexible Ring Binders', 9),
('Ampad Gold Fibre Wirebound Steno Books, 6" x 9", Gregg Ruled', 11),
('Newell 330', 7),
('Post-it “Important Message” Note Pad, Neon Colors, 50 Sheets/Pad', 11),
('Adams Write n Stick Phone Message Book, 11" X 5 1/4", 200 Messages', 11),
('Eldon Simplefile Box Office', 5),
('Avery 489', 3),
('Round Ring Binders', 9),
('Bose SoundLink Bluetooth Speaker', 8),
('Bevis Round Bullnose 29" High Table Top', 4),
('Easy-staple paper', 11),
('Microsoft Arc Touch Mouse', 12),
('Xerox 216', 11),
('GBC VeloBinder Electric Binding Machine', 9),
('Premier Automatic Letter Opener', 15),
('Advantus SlideClip Paper Clips', 14),
('Avery 512', 3),
('Logitech Wireless Gaming Headset G930', 12),
('Bush Westfield Collection Bookcases, Medium Cherry Finish', 1),
('Howard Miller 13" Diameter Goldtone Round Wall Clock', 6),
('Global Deluxe Office Fabric Chairs', 2),
('Eldon ClusterMat Chair Mat with Cordless Antistatic Protection', 6),
('Ibico Laser Imprintable Binding System Covers', 9),
('Vinyl Coated Wire Paper Clips in Organizer Box, 800/Box', 14),
('Xerox 223', 11),
('Tennsco Stur-D-Stor Boltless Shelving, 5 Shelves, 24" Deep, Sand', 5),
('Xerox 1939', 11),
('Floodlight Indoor Halogen Bulbs, 1 Bulb per Pack, 60 Watts', 6),
('Avery Premier Heavy-Duty Binder with Round Locking Rings', 9),
('BPI Conference Tables', 4),
('Electrix 20W Halogen Replacement Bulb for Zoom-In Desk Lamp', 6),
('Newell 350', 7),
('GBC Clear Cover, 8-1/2 x 11, unpunched, 25 covers per pack', 9),
('Boston Heavy-Duty Trimline Electric Pencil Sharpeners', 7),
('Faber Castell Col-Erase Pencils', 7),
('C-Line Cubicle Keepers Polyproplyene Holder With Velcro Backings', 6),
('Hon 4070 Series Pagoda Armless Upholstered Stacking Chairs', 2),
('Eldon Expressions Desk Accessory, Wood Photo Frame, Mahogany', 6),
('Avery 509', 3),
('Deflect-o SuperTray Unbreakable Stackable Tray, Letter, Black', 6),
('AT&T 1070 Corded Phone', 8),
('Xerox 21', 11),
('Boston School Pro Electric Pencil Sharpener, 1670', 7),
('DMI Arturo Collection Mission-style Design Wood Chair', 2),
('Canon imageCLASS MF7460 Monochrome Digital Laser Multifunction Copier', 16),
('NETGEAR N750 Dual Band Wi-Fi Gigabit Router', 12),
('OIC Binder Clips', 14),
('Logitech Wireless Headset h800', 12),
('Telescoping Adjustable Floor Lamp', 6),
('Aastra 57i VoIP phone', 8),
('File Shuttle II and Handi-File, Black', 5),
('Hon 2090 “Pillow Soft” Series Mid Back Swivel/Tilt Chairs', 2),
('Round Specialty Laser Printer Labels', 3),
('GBC Premium Transparent Covers with Diagonal Lined Pattern', 9),
('AT&T 841000 Phone', 8),
('Ibico Recycled Grain-Textured Covers', 9),
('Wilson Jones Custom Binder Spines & Labels', 9),
('Storex Dura Pro Binders', 9),
('Hewlett Packard LaserJet 3310 Copier', 17),
('Avery Non-Stick Binders', 9),
('Tuff Stuff Recycled Round Ring Binders', 9),
('Hon 5100 Series Wood Tables', 4),
('OIC Binder Clips, Mini, 1/4" Capacity, Black', 14),
('Newell 314', 7),
('Square Credit Card Reader, 4 1/2" x 4 1/2" x 1", White', 8),
('BIC Brite Liner Highlighters, Chisel Tip', 7),
('Xerox 1881', 11),
('Acco Hanging Data Binders', 9),
('GBC DocuBind P400 Electric Binding System', 9),
('Sauder Barrister Bookcases', 1),
('#10 Gummed Flap White Envelopes, 100/Box', 13),
('Dixon Prang Watercolor Pencils, 10-Color Set with Brush', 7),
('Adams Phone Message Book, 200 Message Capacity, 8 1/16” x 11”', 11),
('Belkin 8 Outlet SurgeMaster II Gold Surge Protector with Phone Protection', 10),
('Avery Address/Shipping Labels for Typewriters, 4" x 2"', 3),
('Global Ergonomic Managers Chair', 2),
('Newell 333', 7),
('Eldon Wave Desk Accessories', 6),
('Wilson Jones “Snap” Scratch Pad Binder Tool for Ring Binders', 9),
('Staple remover', 15),
('Pizazz Global Quick File', 5),
('Xerox 1930', 11),
('File Shuttle I and Handi-File', 5),
('NETGEAR AC1750 Dual Band Gigabit Smart WiFi Router', 12),
('Newell 324', 7),
('Microsoft Natural Keyboard Elite', 12),
('Xerox 1960', 11),
('Office Impressions End Table, 20-1/2"H x 24"W x 20"D', 4),
('Holmes Odor Grabber', 10),
('Akro-Mils 12-Gallon Tote', 5),
('GBC Twin Loop Wire Binding Elements, 9/16" Spine, Black', 9),
('Southworth Structures Collection', 11),
('Square Ring Data Binders, Rigid 75 Pt. Covers, 11" x 14-7/8"', 9),
('Sony 32GB Class 10 Micro SDHC R40 Memory Card', 12),
('Hon Practical Foundations 30 x 60 Training Table, Light Gray/Charcoal', 4),
('Logitech Media Keyboard K200', 12),
('Lexmark MarkNet N8150 Wireless Print Server', 16),
('3M Hangers With Command Adhesive', 6),
('Crayola Colored Pencils', 7),
('Angle-D Binders with Locking Rings, Label Holders', 9),
('Nortel Meridian M3904 Professional Digital phone', 8),
('Canon PC1080F Personal Copier', 17),
('Wilson Jones Century Plastic Molded Ring Binders', 9),
('Tuf-Vin Binders', 9),
('2300 Heavy-Duty Transfer File Systems by Perma', 5),
('Xerox 1958', 11),
('Acme 10" Easy Grip Assistive Scissors', 15),
('Super Decoflex Portable Personal File', 5),
('Contico 72"H Heavy-Duty Storage System', 5),
('Sony 64GB Class 10 Micro SDHC R40 Memory Card', 12),
('Xerox 1974', 11),
('Avery Hi-Liter EverBold Pen Style Fluorescent Highlighters, 4/Pack', 7),
('Staple holder', 10),
('Sharp AL-1530CS Digital Copier', 17),
('Wirebound Message Book, 4 per Page', 11),
('Bevis Round Conference Table Top, X-Base', 4),
('Wirebound Service Call Books, 5 1/2" x 4"', 11),
('Self-Adhesive Removable Labels', 3),
('Xerox 1908', 11),
('OSullivan 4-Shelf Bookcase in Odessa Pine', 1),
('Novimex High-Tech Fabric Mesh Task Chair', 2),
('Xerox 191', 11),
('Bulldog Vacuum Base Pencil Sharpener', 7),
('Bevis Steel Folding Chairs', 2),
('Xerox 1987', 11),
('American Pencil', 7),
('White Envelopes, White Envelopes with Clear Poly Window', 13),
('KeyTronic 6101 Series - Keyboard - Black', 12),
('Westinghouse Mesh Shade Clip-On Gooseneck Lamp, Black', 6),
('Crate-A-Files', 5),
('Hon Multipurpose Stacking Arm Chairs', 2),
('Coloredge Poster Frame', 6),
('GBC VeloBinder Manual Binding System', 9),
('Epson WorkForce WF-2530 All-in-One Printer, Copier Scanner', 16),
('Design Ebony Sketching Pencil', 7),
('GBC ProClick 150 Presentation Binding System', 9),
('Woodgrain Magazine Files by Perma', 5),
('Letter Size Cart', 5),
('Insertable Tab Post Binder Dividers', 9),
('Belkin QODE FastFit Bluetooth Keyboard', 12),
('Canon Color ImageCLASS MF8580Cdw Wireless Laser All-In-One Printer, Copier, Scanner', 16),
('Xerox 1897', 11),
('Global Deluxe Steno Chair', 2),
('Aluminum Document Frame', 6),
('Fellowes Bankers Box Staxonsteel Drawer File/Stacking System', 5),
('Eldon Mobile Mega Data Cart  Mega Stackable  Add-On Trays', 5),
('Xerox Color Copier Paper, 11" x 17", Ream', 11),
('Office Star - Ergonomically Designed Knee Chair', 2),
('Avery 520', 3),
('GE General Purpose, Extra Long Life, Showcase & Floodlight Incandescent Bulbs', 6),
('Newell 345', 7),
('Fellowes Bankers Box Recycled Super Stor/Drawer', 5),
('Boston 1645 Deluxe Heavier-Duty Electric Pencil Sharpener', 7),
('50 Colored Long Pencils', 7),
('Newell 342', 7),
('Belkin Grip Candy Sheer Case / Cover for iPhone 5 and 5S', 8),
('Deluxe Rollaway Locking File with Drawer', 5),
('Memorex Mini Travel Drive 16 GB USB 2.0 Flash Drive', 12),
('Global Geo Office Task Chair, Gray', 2),
('Hon 4700 Series Mobuis Mid-Back Task Chairs with Adjustable Arms', 2),
('Staple envelope', 13),
('3M Office Air Cleaner', 10),
('Logitech G700s Rechargeable Gaming Mouse', 12),
('Acco D-Ring Binder w/DublLock', 9),
('Bush Advantage Collection Racetrack Conference Table', 4),
('Poly Designer Cover & Back', 9),
('Premier Electric Letter Opener', 15),
('Fellowes Premier Superior Surge Suppressor, 10-Outlet, With Phone and Remote', 10),
('Bush Mission Pointe Library', 1),
('Cardinal Hold-It CD Pocket', 9),
('Eaton Premium Continuous-Feed Paper, 25% Cotton, Letter Size, White, 1000 Shts/Box', 11),
('SAFCO Boltless Steel Shelving', 5),
('Sauder Mission Library with Doors, Fruitwood Finish', 1),
('Samsung Galaxy Note 3', 8),
('Decoflex Hanging Personal Folder File, Blue', 5),
('Recycled Desk Saver Line "While You Were Out" Book, 5 1/2" X 4"', 11),
('Xerox 1912', 11),
('Cisco SPA525G2 IP Phone - Wireless', 8),
('Prang Colored Pencils', 7),
('Fellowes Strictly Business Drawer File, Letter/Legal Size', 5),
('Imation USB 2.0 Swivel Flash Drive USB flash drive - 4 GB - Pink', 12),
('Logitech G602 Wireless Gaming Mouse', 12),
('Alphabetical Labels for Top Tab Filing', 3),
('OSullivan Living Dimensions 2-Shelf Bookcases', 1),
('iHome FM Clock Radio with Lightning Dock', 8),
('Apple iPhone 5S', 8),
('Square Credit Card Reader', 8),
('Logitech M510 Wireless Mouse', 12),
('Fellowes Officeware Wire Shelving', 5),
('Colored Envelopes', 13),
('Sony Micro Vault Click 8 GB USB 2.0 Flash Drive', 12),
('Balt Solid Wood Rectangular Table', 4),
('Strathmore #10 Envelopes, Ultimate White', 13),
('Clear Mylar Reinforcing Strips', 9),
('Howard Miller 14-1/2" Diameter Chrome Round Wall Clock', 6),
('Deflect-O Glasstique Clear Desk Accessories', 6),
('Vinyl Sectional Post Binders', 9),
('GBC Standard Therm-A-Bind Covers', 9),
('Global Troy Executive Leather Low-Back Tilter', 2),
('Storex Flexible Poly Binders with Double Pockets', 9),
('White Dual Perf Computer Printout Paper, 2700 Sheets, 1 Part, Heavyweight, 20 lbs., 14 7/8 x 11', 11),
('Rogers Handheld Barrel Pencil Sharpener', 7),
('Newell 344', 7),
('Personal File Boxes with Fold-Down Carry Handle', 5),
('Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind', 9),
('Executive Impressions Supervisor Wall Clock', 6),
('SanDisk Cruzer 32 GB USB Flash Drive', 12),
('Newell 327', 7),
('Newell 317', 7),
('Canon Image Class D660 Copier', 17),
('Advantus Rolling Storage Box', 5),
('Great White Multi-Use Recycled Paper (20Lb. and 84 Bright)', 11),
('Tennsco Single-Tier Lockers', 5),
('Carina Double Wide Media Storage Towers in Natural & Black', 5),
('XtraLife ClearVue Slant-D Ring Binders by Cardinal', 9),
('Motorola HK250 Universal Bluetooth Headset', 8),
('Imation 16GB Mini TravelDrive USB 2.0 Flash Drive', 12),
('Staples', 14),
('Global Commerce Series High-Back Swivel/Tilt Chairs', 2),
('Eldon Gobal File Keepers', 5),
('Martin Yale Chadless Opener Electric Letter Opener', 15),
('White Business Envelopes with Contemporary Seam, Recycled White Business Envelopes', 13),
('Safco Contoured Stacking Chairs', 2),
('Tenex Chairmats For Use With Carpeted Floors', 6),
('Panasonic KX-TG9471B', 8),
('Sterilite Officeware Hinged File Box', 5),
('Premier Elliptical Ring Binder, Black', 9),
('Cardinal Poly Pocket Divider Pockets for Ring Binders', 9),
('Eureka The Boss Cordless Rechargeable Stick Vac', 10),
('Situations Contoured Folding Chairs, 4/Set', 2),
('Enermax Aurora Lite Keyboard', 12),
('LG Electronics Tone+ HBS-730 Bluetooth Headset', 8),
('SanDisk Cruzer 64 GB USB Flash Drive', 12),
('Xblue XB-1670-86 X16 Small Office Telephone - Titanium', 8),
('Deflect-o EconoMat Studded, No Bevel Mat for Low Pile Carpeting', 6),
('Avery Printable Repositionable Plastic Tabs', 9),
('Xerox 1898', 11),
('Staple remover', 15),
('HON 5400 Series Task Chairs for Big and Tall', 2),
('Howard Miller 11-1/2" Diameter Grantwood Wall Clock', 6),
('Advantus T-Pin Paper Clips', 14),
('Tennsco 16-Compartment Lockers with Coat Rack', 5),
('Zebra Zazzle Fluorescent Highlighters', 7),
('Avery 473', 3),
('Bretford “Just In Time” Height-Adjustable Multi-Task Work Tables', 4),
('Xerox 226', 11),
('GBC Prepunched Paper, 19-Hole, for Binding Systems, 24-lb', 9),
('Sanitaire Vibra Groomer IR Commercial Upright Vacuum, Replacement Belts', 10),
('Advantus Panel Wall Acrylic Frame', 6),
('Alliance Big Bands Rubber Bands, 12/Pack', 14),
('Cisco SPA301', 8),
('Personal Creations Ink Jet Cards and Labels', 11),
('GBC White Gloss Covers, Plain Front', 9),
('Xerox 222', 11),
('Hon Every-Day Series Multi-Task Chairs', 2),
('Cush Cases Heavy Duty Rugged Cover Case for Samsung Galaxy S5 - Purple', 8),
('Newell 332', 7),
('Rediform S.O.S. Phone Message Books', 11),
('Acme Value Line Scissors', 15),
('Contract Clock, 14", Brown', 6),
('Martin-Yale Premier Letter Opener', 15),
('AT&T SB67148 SynJ', 8),
('Recycled Pressboard Report Cover with Reinforced Top Hinge', 9),
('Dot Matrix Printer Tape Reel Labels, White, 5000/Box', 3),
('i.Sound Portable Power - 8000 mAh', 8),
('Xerox 225', 11),
('Xerox 1894', 11),
('Newell 312', 7),
('Fellowes Superior 10 Outlet Split Surge Protector', 10),
('Dana Halogen Swing-Arm Architect Lamp', 6),
('Acme Stainless Steel Office Snips', 15),
('Mophie Juice Pack Helium for iPhone', 8),
('GE 2-Jack Phone Line Splitter', 8),
('Hot File 7-Pocket, Floor Stand', 5),
('Xerox 1889', 11),
('Angle-D Ring Binders', 9),
('Motorola L804', 8),
('Avery 493', 3),
('Xerox 1972', 11),
('Cisco 8x8 Inc. 6753i IP Business Phone System', 8),
('Prestige Round Ring Binders', 9),
('DAX Metal Frame, Desktop, Stepped-Edge', 6),
('DAX Value U-Channel Document Frames, Easel Back', 6),
('Recycled Easel Ring Binders', 9),
('Grandstream GXP1160 VoIP phone', 8),
('Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl', 9),
('Global Managers Adjustable Task Chair, Storm', 2),
('Honeywell Enviracaire Portable HEPA Air Cleaner for up to 10 x 16 Room', 10),
('Mini 13-1/2 Capacity Data Binder Rack, Pearl', 5),
('Master Caster Door Stop, Brown', 6),
('Belkin Premiere Surge Master II 8-outlet surge protector', 10),
('Acco Pressboard Covers with Storage Hooks, 9 1/2" x 11", Executive Red', 9),
('Tennsco Regal Shelving Units', 5),
('Imation 32GB Pocket Pro USB 3.0 Flash Drive - 32 GB - Black - 1 P ...', 12),
('Jabra SPEAK 410', 8),
('Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 1/Pack', 12),
('Office Star - Mesh Screen back chair with Vinyl seat', 2),
('Premium Transparent Presentation Covers by GBC', 9),
('Tripp Lite TLP810NET Broadband Surge for Modem/Fax', 10),
('Wilson Jones Turn Tabs Binder Tool for Ring Binders', 9),
('Eldon 200 Class Desk Accessories', 6),
('Economy Rollaway Files', 5),
('Avery 480', 3),
('Xerox 1993', 11),
('Eureka The Boss Plus 12-Amp Hard Box Upright Vacuum, Red', 10),
('Staples', 14),
('Belkin F9H710-06 7 Outlet SurgeMaster Surge Protector', 10),
('First Data FD10 PIN Pad', 12),
('Sony 16GB Class 10 Micro SDHC R40 Memory Card', 12),
('Tripp Lite Isotel 8 Ultra 8 Outlet Metal Surge', 10),
('Avery Durable Poly Binders', 9),
('Airmail Envelopes', 13),
('Space Solutions Commercial Steel Shelving', 5),
('Acme Tagit Stainless Steel Antibacterial Scissors', 15),
('ClearOne Communications CHAT 70 OC Speaker Phone', 8),
('Master Giant Foot Doorstop, Safety Yellow', 6),
('12-1/2 Diameter Round Wall Clock', 6),
('Chromcraft Bull-Nose Wood Round Conference Table Top, Wood Base', 4),
('Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4"X8 1/2", 200/Messages', 11),
('Newell 331', 7),
('Kensington 6 Outlet Guardian Standard Surge Protector', 10),
('Southworth 100% Résumé Paper, 24lb.', 11),
('Hoover Portapower Portable Vacuum', 10),
('Verbatim 25 GB 6x Blu-ray Single Layer Recordable Disc, 10/Pack', 12),
('Howard Miller 13-1/2" Diameter Rosebrook Wall Clock', 6),
('Ibico Hi-Tech Manual Binding System', 9),
('Avery Hanging File Binders', 9),
('Fellowes Neat Ideas Storage Cubes', 5),
('Cubify CubeX 3D Printer Triple Head Print', 16),
('Avery 516', 3),
('Bush Andora Bookcase, Maple/Graphite Gray Finish', 1),
('Luxo Professional Magnifying Clamp-On Fluorescent Lamps', 6),
('Recycled Eldon Regeneration Jumbo File', 5),
('Imation Bio 8GB USB Flash Drive Imation Corp', 12),
('Xerox 1977', 11),
('Avery 490', 3),
('Avery 4027 File Folder Labels for Dot Matrix Printers, 5000 Labels per Box, White', 3),
('Binney & Smith Crayola Metallic Crayons, 16-Color Pack', 7),
('GBC Linen Binding Covers', 9),
('Tenex "The Solids" Textured Chair Mats', 6),
('Laminate Occasional Tables', 4),
('Xerox 220', 11),
('Fellowes 8 Outlet Superior Workstation Surge Protector', 10),
('OSullivan Living Dimensions 5-Shelf Bookcases', 1),
('#10- 4 1/8" x 9 1/2" Security-Tint Envelopes', 13),
('Bionaire Personal Warm Mist Humidifier/Vaporizer', 10),
('Logitech Wireless Performance Mouse MX for PC and Mac', 12),
('Cardinal Holdit Business Card Pockets', 9),
('Howard Miller 13" Diameter Pewter Finish Round Wall Clock', 6),
('Tops Green Bar Computer Printout Paper', 11),
('Chromcraft Bull-Nose Wood Oval Conference Tables & Bases', 4),
('Recycled Data-Pak for Archival Bound Computer Printouts, 12-1/2 x 12-1/2 x 16', 5),
('Seth Thomas 16" Steel Case Clock', 6),
('Acme Softgrip Scissors', 15),
('Manila Recycled Extra-Heavyweight Clasp Envelopes, 6" x 9"', 13),
('ClearSounds CSC500 Amplified Spirit Phone Corded phone', 8),
('Xerox 1964', 11),
('Bevis Traditional Conference Table Top, Plinth Base', 4),
('Personal Folder Holder, Ebony', 5),
('Logitech Illuminated - Keyboard', 12),
('OSullivan Cherrywood Estates Traditional Bookcase', 1),
('Acco Translucent Poly Ring Binders', 9),
('Logitech Wireless Touch Keyboard K400', 12),
('Avery 508', 3),
('GBC Standard Plastic Binding Systems Combs', 9),
('Xerox 196', 11),
('Fiskars 8" Scissors, 2/Pack', 15),
('Belkin iPhone and iPad Lightning Cable', 8),
('GBC Durable Plastic Covers', 9),
('Nu-Dell Leatherette Frames', 6),
('Avery Durable Binders', 9),
('Hewlett Packard 610 Color Digital Copier / Printer', 17),
('Chromcraft Round Conference Tables', 4),
('Avery 476', 3),
('Brown Kraft Recycled Envelopes', 13),
('Plantronics S12 Corded Telephone Headset System', 12),
('3-ring staple pack', 9),
('Fellowes Stor/Drawer Steel Plus Storage Drawers', 5),
('Electrix Halogen Magnifier Lamp', 6),
('Hon 4070 Series Pagoda Round Back Stacking Chairs', 2),
('Cardinal EasyOpen D-Ring Binders', 9),
('GBC Instant Report Kit', 9),
('Boston 19500 Mighty Mite Electric Pencil Sharpener', 7),
('C-Line Magnetic Cubicle Keepers, Clear Polypropylene', 6),
('Dixon My First Ticonderoga Pencil, #2', 7),
('Hon GuestStacker Chair', 2),
('Xerox 1927', 11),
('Safco Value Mate Series Steel Bookcases, Baked Enamel Finish on Steel, Gray', 1),
('Microsoft Natural Ergonomic Keyboard 4000', 12),
('Cameo Buff Policy Envelopes', 13),
('Heavy-Duty E-Z-D Binders', 9),
('Lifetime Advantage Folding Chairs, 4/Carton', 2),
('Acco PRESSTEX Data Binder with Storage Hooks, Dark Blue, 9 1/2" X 11"', 9),
('Office Star - Contemporary Task Swivel Chair', 2),
('Cisco Unified IP Phone 7945G VoIP phone', 8),
('Avery 499', 3),
('Xerox 1887', 11),
('Smead Alpha-Z Color-Coded Second Alphabetical Labels and Starter Set', 3),
('Executive Impressions 14" Contract Wall Clock', 6),
('Belkin 7 Outlet SurgeMaster II', 10),
('Xerox 218', 11),
('Eldon Stackable Tray, Side-Load, Legal, Smoke', 6),
('Model L Table or Wall-Mount Pencil Sharpener', 7),
('ClearOne CHATAttach 160 - speaker phone', 8),
('Kensington SlimBlade Notebook Wireless Mouse with Nano Receiver', 12),
('Newell 32', 7),
('Belkin F9G930V10-GRY 9 Outlet Surge', 10),
('Razer Tiamat Over Ear 7.1 Surround Sound PC Gaming Headset', 12),
('Xerox 1968', 11),
('Self-Adhesive Ring Binder Labels', 9),
('Global Leather Executive Chair', 2),
('GBC Recycled Grain Textured Covers', 9),
('Xerox 1941', 11),
('Razer Kraken PRO Over Ear PC and Music Headset', 12),
('Kingston Digital DataTraveler 32GB USB 2.0', 12),
('Advantus Plastic Paper Clips', 14),
('Acme Forged Steel Scissors with Black Enamel Handles', 15),
('Security-Tint Envelopes', 13),
('Global Airflow Leather Mesh Back Chair, Black', 2),
('Fellowes Smart Surge Ten-Outlet Protector, Platinum', 10),
('Pyle PMP37LED', 8),
('Clarity 53712', 8),
('Boston 16801 Nautilus Battery Pencil Sharpener', 7),
('Holmes Replacement Filter for HEPA Air Cleaner, Large Room', 10),
('Zebra GX420t Direct Thermal/Thermal Transfer Printer', 16),
('GBC ProClick Punch Binding System', 9),
('Adams Telephone Message Books, 5 1/4” x 11”', 11),
('Newell 335', 7),
('OSullivan 3-Shelf Heavy-Duty Bookcases', 1),
('Fellowes Binding Cases', 9),
('Ibico Plastic and Wire Spiral Binding Combs', 9),
('Acme Preferred Stainless Steel Scissors', 15),
('Avery 486', 3),
('Linden 10" Round Wall Clock, Black', 6),
('Maxell DVD-RAM Discs', 12),
('DIXON Oriole Pencils', 7),
('Xerox 202', 11),
('Xerox 1884', 11),
('Acme Box Cutter Scissors', 15),
('Staple magnet', 5),
('Deluxe Chalkboard Eraser Cleaner', 7),
('Logitech MX Performance Wireless Mouse', 12),
('Newell 337', 7),
('Logitech B530 USB Headset - headset - Full size, Binaural', 8),
('Avery 482', 3),
('Howard Miller 11-1/2" Diameter Ridgewood Wall Clock', 6),
('Avery 483', 3),
('Large Capacity Hanging Post Binders', 9),
('GBC Ibimaster 500 Manual ProClick Binding System', 9),
('Southworth 100% Cotton The Best Paper', 11),
('Xerox 1910', 11),
('Logitech G19 Programmable Gaming Keyboard', 12),
('Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Light Blue', 9),
('Lock-Up Easel Spel-Binder', 9),
('Dax Clear Box Frame', 6),
('Fellowes Black Plastic Comb Bindings', 9),
('Eldon Shelf Savers Cubes and Bins', 5),
('Anker Ultrathin Bluetooth Wireless Keyboard Aluminum Cover with Stand', 12),
('Ampad Poly Cover Wirebound Steno Book, 6" x 9" Assorted Colors, Gregg Ruled', 11),
('Fluorescent Highlighters by Dixon', 7),
('Nortel Networks T7316 E Nt8 B27', 8),
('Binding Machine Supplies', 9),
('Staple envelope', 13),
('Things To Do Today Pad', 11),
('Wilson Jones Hanging Recycled Pressboard Data Binders', 9),
('Permanent Self-Adhesive File Folder Labels for Typewriters by Universal', 3),
('Deluxe Heavy-Duty Vinyl Round Ring Binder', 9),
('Xerox 1923', 11),
('Xerox 1931', 11),
('Bush Westfield Collection Bookcases, Fully Assembled', 1),
('Gear Head AU3700S Headset', 8),
('Wilson Jones Legal Size Ring Binders', 9),
('Polycom CX600 IP Phone VoIP phone', 8),
('Maxell iVDR EX 500GB Cartridge', 12),
('Fellowes High-Stak Drawer Files', 5),
('Lesro Sheffield Collection Coffee Table, End Table, Center Table, Corner Table', 4),
('Acco Perma 4000 Stacking Storage Drawers', 5),
('Maxell 4.7GB DVD-R', 12),
('OtterBox Commuter Series Case - iPhone 5 & 5s', 8),
('Kensington 4 Outlet MasterPiece Compact Power Control Center', 10),
('Xerox 1985', 11),
('Hypercom P1300 Pinpad', 12),
('Sanford Prismacolor Professional Thick Lead Art Pencils, 36-Color Set', 7),
('RSVP Cards & Envelopes, Blank White, 8-1/2" X 11", 24 Cards/25 Envelopes/Set', 11),
('Wirebound Message Books, 2 7/8" x 5", 3 Forms per Page', 11),
('JM Magazine Binder', 9),
('Xerox 213', 11),
('Fellowes 8 Outlet Superior Workstation Surge Protector w/o Phone/Fax/Modem Protection', 10),
('Message Book, Standard Line "While You Were Out", 5 1/2" X 4", 200 Sets/Book', 11),
('Acco Pressboard Covers with Storage Hooks, 14 7/8" x 11", Dark Blue', 9),
('Standard Rollaway File with Lock', 5),
('Avery Trapezoid Extra Heavy Duty 4" Binders', 9),
('Bevis Boat-Shaped Conference Table', 4),
('Deflect-o RollaMat Studded, Beveled Mat for Medium Pile Carpeting', 6),
('Riverside Furniture Oval Coffee Table, Oval End Table, End Table with Drawer', 4),
('Xerox 210', 11),
('Staple-based wall hangings', 6),
('Avery Durable Slant Ring Binders', 9),
('Universal Ultra Bright White Copier/Laser Paper, 8 1/2" x 11", Ream', 11),
('Luxo Professional Combination Clamp-On Lamps', 6),
('Zipper Ring Binder Pockets', 9),
('Avery File Folder Labels', 3),
('Color-Coded Legal Exhibit Labels', 3),
('Xerox 212', 11),
('Computer Printout Paper with Letter-Trim Fine Perforations', 11),
('Office Impressions Heavy Duty Welded Shelving & Multimedia Storage Drawers', 5),
('DAX Black Cherry Wood-Tone Poster Frame', 6),
('Wilson Jones Easy Flow II Sheet Lifters', 9),
('Xerox 188', 11),
('BIC Brite Liner Grip Highlighters, Assorted, 5/Pack', 7),
('Samsung Galaxy S III - 16GB - pebble blue (T-Mobile)', 8),
('#10- 4 1/8" x 9 1/2" Recycled Envelopes', 13),
('Wasp CCD Handheld Bar Code Reader', 16),
('Acco Suede Grain Vinyl Round Ring Binder', 9),
('Bulldog Table or Wall-Mount Pencil Sharpener', 7),
('Xerox 1979', 11),
('Fellowes PB300 Plastic Comb Binding Machine', 9),
('Plantronics Voyager Pro Legend', 8),
('Laser & Ink Jet Business Envelopes', 13),
('Portable Personal File Box', 5),
('Magna Visual Magnetic Picture Hangers', 6),
('Plantronics CS510 - Over-the-Head monaural Wireless Headset System', 12),
('Fellowes Super Stor/Drawer Files', 5),
('UniKeep View Case Binders', 9),
('Eldon Delta Triangular Chair Mat, 52" x 58", Clear', 6),
('Project Tote Personal File', 5),
('Enermax Acrylux Wireless Keyboard', 12),
('G.E. Halogen Desk Lamp Bulbs', 6),
('OtterBox Commuter Series Case - Samsung Galaxy S4', 8),
('Iceberg Mobile Mega Data/Printer Cart', 5),
('Staples in misc. colors', 7),
('Global Comet Stacking Arm Chair', 2),
('Cisco SPA525G2 5-Line IP Phone', 16),
('Peel & Seel Envelopes', 13),
('GBC Plastic Binding Combs', 9),
('Xerox 2', 11),
('Xerox 1935', 11),
('Cyber Acoustics AC-202b Speech Recognition Stereo Headset', 8),
('Cisco SPA508G', 8),
('Avery 514', 3),
('Southworth 25% Cotton Granite Paper & Envelopes', 11),
('Eldon Advantage Chair Mats for Low to Medium Pile Carpets', 6),
('Aluminum Screw Posts', 9),
('Newell 336', 7),
('Staples in misc. colors', 7),
('Maxell 4.7GB DVD+RW 3/Pack', 12),
('Atlantic Metals Mobile 5-Shelf Bookcases, Custom Colors', 1),
('Quartet Alpha White Chalk, 12/Pack', 7),
('Belkin F9S820V06 8 Outlet Surge', 10),
('Global Stack Chair without Arms, Black', 2),
('Eldon Antistatic Chair Mats for Low to Medium Pile Carpets', 6),
('Important Message Pads, 50 4-1/4 x 5-1/2 Forms per Pad', 11),
('Howard Miller 12" Round Wall Clock', 6),
('DIXON Ticonderoga Erasable Checking Pencils', 7),
('Eldon Advantage Foldable Chair Mats for Low Pile Carpets', 6),
('Avery Round Ring Poly Binders', 9),
('Avery Hole Reinforcements', 9),
('Wilson Jones Ledger-Size, Piano-Hinge Binder, 2", Blue', 9),
('Stockwell Gold Paper Clips', 14),
('Super Bands, 12/Pack', 14),
('Plantronics 81402', 8),
('Assorted Color Push Pins', 14),
('GBC Velobind Prepunched Cover Sets, Regency Series', 9),
('3M Organizer Strips', 9),
('Avery Durable Slant Ring Binders With Label Holder', 9),
('Micropad Numeric Keypads', 12),
('Newell 328', 7),
('Belkin 8 Outlet SurgeMaster II Gold Surge Protector', 10),
('Easy-staple paper', 11),
('Global High-Back Leather Tilter, Burgundy', 2),
('Easy-staple paper', 11),
('Ativa V4110MDD Micro-Cut Shredder', 16),
('Xerox 224', 11),
('Avery 488', 3),
('Innergie mMini Combo Duo USB Travel Charging Kit', 8),
('Stanley Contemporary Battery Pencil Sharpeners', 7),
('AT&T 1080 Corded phone', 8),
('Xerox 1950', 11),
('Fellowes Mobile File Cart, Black', 5),
('GBC Recycled VeloBinder Covers', 9),
('Hon 4060 Series Tables', 4),
('Newell 326', 7),
('Logitech ClearChat Comfort/USB Headset H390', 12),
('Newell 346', 7),
('Rediform Wirebound "Phone Memo" Message Book, 11 x 5-3/4', 11),
('GBC Standard Recycled Report Covers, Clear Plastic Sheets', 9),
('Staples', 14),
('Recycled Interoffice Envelopes with Re-Use-A-Seal Closure, 10 x 13', 13),
('invisibleSHIELD by ZAGG Smudge-Free Screen Protector', 8),
('Xerox 1905', 11),
('Bush Saratoga Collection 5-Shelf Bookcase, Hanover Cherry, *Special Order', 1),
('Ampad Evidence Wirebond Steno Books, 6" x 9"', 11),
('Apple iPhone 5C', 8),
('Newell 351', 7),
('Staple envelope', 13),
('KI Adjustable-Height Table', 4),
('Xerox 1945', 11),
('Avery 502', 3),
('Steel Personal Filing/Posting Tote', 5),
('Tyvek  Top-Opening Peel & Seel  Envelopes, Gray', 13),
('Xerox 1896', 11),
('Cardinal Slant-D Ring Binders', 9),
('Stockwell Push Pins', 14),
('Star Micronics TSP800 TSP847IIU Receipt Printer', 16),
('Hoover Shoulder Vac Commercial Portable Vacuum', 10),
('Staples', 14),
('Acco Expandable Hanging Binders', 9),
('Shocksock Galaxy S4 Armband', 8),
('Brother DCP1000 Digital 3 in 1 Multifunction Machine', 17),
('Eldon Regeneration Recycled Desk Accessories, Smoke', 6),
('Crayola Anti Dust Chalk, 12/Pack', 7),
('SAFCO Commercial Wire Shelving, 72h', 5),
('Chromcraft 48" x 96" Racetrack Double Pedestal Table', 4),
('Hon Deluxe Fabric Upholstered Stacking Chairs', 2),
('Belkin 325VA UPS Surge Protector, 6', 10),
('PowerGen Dual USB Car Charger', 8),
('Cardinal HOLDit! Binder Insert Strips,Extra Strips', 9),
('C-Line Cubicle Keepers Polyproplyene Holder w/Velcro Back, 8-1/2x11, 25/Bx', 6),
('Xerox 1996', 11),
('Iris Project Case', 5),
('Geographics Note Cards, Blank, White, 8 1/2" x 11"', 11),
('ACCOHIDE Binder by Acco', 9),
('Avery 3 1/2" Diskette Storage Pages, 10/Pack', 9),
('Staple-on labels', 3),
('Harbour Creations Steel Folding Chair', 2),
('Wireless Extenders zBoost YX545 SOHO Signal Booster', 8),
('OIC #2 Pencils, Medium Soft', 7),
('Sannysis Cute Owl Design Soft Skin Case Cover for Samsung Galaxy S4', 8),
('Peel & Stick Add-On Corner Pockets', 9),
('Carina 42"Hx23 3/4"W Media Storage Unit', 5),
('Toshiba IPT2010-SD IP Telephone', 8),
('GuestStacker Chair with Chrome Finish Legs', 2),
('Xerox 1924', 11),
('Ultra Door Push Plate', 6),
('Kensington Orbit Wireless Mobile Trackball for PC and Mac', 12),
('Global Chrome Stack Chair', 2),
('Sauder Facets Collection Locker/File Cabinet, Sky Alder Finish', 5),
('Newell 315', 7),
('Pressboard Data Binders by Wilson Jones', 9),
('Wilson Jones Standard D-Ring Binders', 9),
('Eldon Expressions Punched Metal & Wood Desk Accessories, Pewter & Cherry', 6),
('Samsung Galaxy Note 2', 8),
('GE DSL Phone Line Filter', 8),
('Easy-staple paper', 11),
('Carina Media Storage Towers in Natural & Black', 5),
('Fellowes Econo/Stor Drawers', 5),
('SANFORD Liquid Accent Tank-Style Highlighters', 7),
('Blue String-Tie & Button Interoffice Envelopes, 10 x 13', 13),
('Canon Imageclass D680 Copier / Fax', 17),
('24-Hour Round Wall Clock', 6),
('Eldon Radial Chair Mat for Low to Medium Pile Carpets', 6),
('Eldon Image Series Desk Accessories, Ebony', 6),
('Sanford 52201 APSCO Electric Pencil Sharpener', 7),
('Samsung Replacement EH64AVFWE Premium Headset', 8),
('GBC DocuBind P100 Manual Binding Machine', 9),
('Fashion Color Clasp Envelopes', 13),
('Hon Non-Folding Utility Tables', 4),
('Bestar Classic Bookcase', 1),
('Staples in misc. colors', 7),
('Office Star - Contemporary Swivel Chair with Padded Adjustable Arms and Flex Back', 2),
('Sanford Pocket Accent Highlighters', 7),
('Mitel MiVoice 5330e IP Phone', 8),
('Westinghouse Clip-On Gooseneck Lamps', 6),
('Howard Miller Distant Time Traveler Alarm Clock', 6),
('Tennsco Double-Tier Lockers', 5),
('Wilson SignalBoost 841262 DB PRO Amplifier Kit', 8),
('XtraLife ClearVue Slant-D Ring Binder, White, 3"', 9),
('Pencil and Crayon Sharpener', 7),
('Ampad Phone Message Book, Recycled, 400 Message Capacity, 5 ¾” x 11”', 11),
('Fellowes Bankers Box Stor/Drawer Steel Plus', 5),
('Performers Binder/Pad Holder, Black', 9),
('Office Star Flex Back Scooter Chair with White Frame', 2),
('Logitech G13 Programmable Gameboard with LCD Display', 12),
('Panasonic KP-380BK Classic Electric Pencil Sharpener', 7),
('Memorex Froggy Flash Drive 4 GB', 12),
('Maxell 74 Minute CD-R Spindle, 50/Pack', 12),
('Geemarc AmpliPOWER60', 8),
('Avery 48', 3),
('Avery Arch Ring Binders', 9),
('Xerox 1915', 11),
('Avery Reinforcements for Hole-Punch Pages', 9),
('Colorific Watercolor Pencils', 7),
('BIC Liqua Brite Liner', 7),
('ACCOHIDE 3-Ring Binder, Blue, 1"', 9),
('Xerox 1973', 11),
('GBC Binding covers', 9),
('Sauder Cornerstone Collection Library', 1),
('Westinghouse Floor Lamp with Metal Mesh Shade, Black', 6),
('Blue Parrot B250XT Professional Grade Wireless Bluetooth Headset with', 8),
('Belkin 6 Outlet Metallic Surge Strip', 10),
('Hon Valutask Swivel Chairs', 2),
('Avery 517', 3),
('Avery 477', 3),
('Eureka Recycled Copy Paper 8 1/2" x 11", Ream', 11),
('Seth Thomas 12" Clock w/ Goldtone Case', 6),
('Memorex Froggy Flash Drive 8 GB', 12),
('Acco 6 Outlet Guardian Premium Surge Suppressor', 10),
('Avoid Verbal Orders Carbonless Minifold Book', 11),
('Fellowes Presentation Covers for Comb Binding Machines', 9),
('Panasonic KP-310 Heavy-Duty Electric Pencil Sharpener', 7),
('Holmes Cool Mist Humidifier for the Whole House with 8-Gallon Output per Day, Extended Life Filter', 10),
('SAFCO Commercial Wire Shelving, Black', 5),
('Tensor Computer Mounted Lamp', 6),
('Polycom SoundPoint IP 450 VoIP phone', 8),
('Rediform S.O.S. 1-Up Phone Message Bk, 4-1/4x3-1/16 Bk, 1 Form/Pg, 40 Messages/Bk, 3/Pk', 11),
('Cisco CP-7937G Unified IP Conference Station Phone', 16),
('Boston 16701 Slimline Battery Pencil Sharpener', 7),
('Avery 494', 3),
('Memo Book, 100 Message Capacity, 5 3/8” x 11”', 11),
('Newell 35', 7),
('Wilson Jones 14 Line Acrylic Coated Pressboard Data Binders', 9),
('Avery Non-Stick Heavy Duty View Round Locking Ring Binders', 9),
('Hanging Personal Folder File', 5),
('Xerox 1909', 11),
('Leather Task Chair, Black', 2),
('Its Hot Message Books with Stickers, 2 3/4" x 5"', 11),
('Digium D40 VoIP phone', 8),
('DYMO CardScan Personal V9 Business Card Scanner', 16),
('Case Logic 2.4GHz Wireless Keyboard', 12),
('Logitech Desktop MK120 Mouse and keyboard Combo', 12),
('Pressboard Data Binder, Crimson, 12" X 8 1/2"', 9),
('Lesro Round Back Collection Coffee Table, End Table', 4),
('Hoover WindTunnel Plus Canister Vacuum', 10),
('Xerox 1934', 11),
('Newell 329', 7),
('Panasonic KX T7731-B Digital phone', 8),
('Safco Wire Cube Shelving System, For Use as 4 or 5 14" Cubes, Black', 5),
('White Computer Printout Paper by Universal', 11),
('Revere Boxed Rubber Bands by Revere', 14),
('Eldon 200 Class Desk Accessories, Black', 6),
('Ames Color-File Green Diamond Border X-ray Mailers', 13),
('Bevis Oval Conference Table, Walnut', 4),
('Hon 61000 Series Interactive Training Tables', 4),
('Acco PRESSTEX Data Binder with Storage Hooks, Light Blue, 9 1/2" X 11"', 9),
('Xerox 217', 11),
('Bush Andora Conference Table, Maple/Graphite Gray Finish', 4),
('Xerox 189', 11),
('KI Adjustable-Height Table', 4),
('Panasonic KP-150 Electric Pencil Sharpener', 7),
('GBC Recycled Regency Composition Covers', 9),
('DAX Executive Solid Wood Document Frame, Desktop or Hang, Mahogany, 5 x 7', 6),
('ShoreTel ShorePhone IP 230 VoIP phone', 8),
('Petty Cash Envelope', 11),
('3M Replacement Filter for Office Air Cleaner for 20 x 33 Room', 10),
('Samsung Rugby III', 8),
('Acco Four Pocket Poly Ring Binder with Label Holder, Smoke, 1"', 9),
('Canvas Sectional Post Binders', 9),
('Strathmore Photo Mount Cards', 11),
('Xerox 203', 11),
('Plantronics Audio 995 Wireless Stereo Headset', 12),
('Storex Dura Pro Binders', 9),
('Xerox 1948', 11),
('Global Super Steno Chair', 2),
('OtterBox Defender Series Case - Samsung Galaxy S4', 8),
('Wilson Jones Suede Grain Vinyl Binders', 9),
('OtterBox Defender Series Case - iPhone 5c', 8),
('Wilson Jones DublLock D-Ring Binders', 9),
('Surelock Post Binders', 9),
('Hewlett-Packard Deskjet 3050a All-in-One Color Inkjet Printer', 16),
('Ibico Plastic Spiral Binding Combs', 9),
('Iceberg OfficeWorks 42" Round Tables', 4),
('DAX Wood Document Frame', 6),
('Wilson Jones Heavy-Duty Casebound Ring Binders with Metal Hinges', 9),
('Global Executive Mid-Back Managers Chair', 2),
('Xerox 1946', 11),
('Newell 320', 7),
('Eldon Image Series Desk Accessories, Burgundy', 6),
('Newell 340', 7),
('Avery 506', 3),
('Xerox 192', 11),
('HP Office Recycled Paper (20Lb. and 87 Bright)', 11),
('X-Rack File for Hanging Folders', 5),
('Xerox 199', 11),
('WD My Passport Ultra 500GB Portable External Hard Drive', 12),
('Staples', 14),
('Cisco IP Phone 7961G-GE VoIP phone', 8),
('Logitech Trackman Marble Mouse', 12),
('Adams Telephone Message Book W/Dividers/Space For Phone Numbers, 5 1/4"X8 1/2", 300/Messages', 11),
('Acco Perma 3000 Stacking Storage Drawers', 5),
('Xerox 197', 11),
('iKross Bluetooth Portable Keyboard + Cell Phone Stand Holder + Brush for Apple iPhone 5S 5C 5, 4S 4', 8),
('Hon 2111 Invitation Series Corner Table', 4),
('Lexmark X 9575 Professional All-in-One Color Printer', 16),
('Ibico Covers for Plastic or Wire Binding Elements', 9),
('Newell 325', 7),
('Xerox 1970', 11),
('12 Colored Short Pencils', 7),
('Master Caster Door Stop, Large Neon Orange', 6),
('Rubber Band Ball', 14),
('Loose Memo Sheets', 11),
('Xerox 1988', 11),
('Neat Ideas Personal Hanging Folder Files, Black', 5),
('Belkin OmniView SE Rackmount Kit', 5),
('Rogers Jumbo File, Granite', 5),
('Commercial WindTunnel Clean Air Upright Vacuum, Replacement Belts, Filtration Bags', 10),
('Eldon Wave Desk Accessories', 6),
('Tenex Personal Self-Stacking Standard File Box, Black/Gray', 5),
('Hoover Commercial Soft Guard Upright Vacuum And Disposable Filtration Bags', 10),
('Avery 481', 3),
('Newell 310', 7),
('Staple envelope', 13),
('Newell 319', 7),
('Avery 518', 3),
('Sensible Storage WireTech Storage Systems', 5),
('Kingston Digital DataTraveler 16GB USB 2.0', 12),
('GBC Imprintable Covers', 9),
('Newell 347', 7),
('Pastel Pink Envelopes', 13),
('Belkin F8E887 USB Wired Ergonomic Keyboard', 12),
('ARKON Windshield Dashboard Air Vent Car Mount Holder', 8),
('Xerox 1949', 11),
('Conquest 14 Commercial Heavy-Duty Upright Vacuum, Collection System, Accessory Kit', 10),
('Xerox 1886', 11),
('Acco Clips to Go Binder Clips, 24 Clips in Two Sizes', 14),
('Dixon Ticonderoga Erasable Colored Pencil Set, 12-Color', 7),
('Pyle PRT45 Retro Home Telephone', 8),
('Spiral Phone Message Books with Labels by Adams', 11),
('Sauder Inglewood Library Bookcases', 1),
('Xerox 1901', 11),
('Acme Elite Stainless Steel Scissors', 15),
('Tenex 46" x 60" Computer Anti-Static Chairmat, Rectangular Shaped', 6),
('Prang Drawing Pencil Set', 7),
('BOSTON Ranger #55 Pencil Sharpener, Black', 7),
('Newell 307', 7),
('Panasonic KP-4ABK Battery-Operated Pencil Sharpener', 7),
('Avery Binder Labels', 9),
('VTech DS6151', 8),
('V7 USB Numeric Keypad', 12),
('Peel-Off China Markers', 7),
('Acco Perma 2700 Stacking Storage Drawers', 5),
('Wirebound Message Books, Four 2 3/4 x 5 White Forms per Page', 11),
('GE 48" Fluorescent Tube, Cool White Energy Saver, 34 Watts, 30/Box', 6),
('Micro Innovations USB RF Wireless Keyboard with Mouse', 12),
('Plantronics Savi W720 Multi-Device Wireless Headset System', 12),
('Stacking Tray, Side-Loading, Legal, Smoke', 6),
('Smead Adjustable Mobile File Trolley with Lockable Top', 5),
('Jawbone MINI JAMBOX Wireless Bluetooth Speaker', 8),
('Weyerhaeuser First Choice Laser/Copy Paper (20Lb. and 88 Bright)', 11),
('Canon PC940 Copier', 17),
('Multicolor Computer Printout Paper', 11),
('Brites Rubber Bands, 1 1/2 oz. Box', 14),
('Catalog Binders with Expanding Posts', 9),
('Grandstream GXP2100 Mainstream Business Phone', 8),
('Xerox 1940', 11),
('Xerox 1986', 11),
('Binder Clips by OIC', 14),
('Wilson Jones 1" Hanging DublLock Ring Binders', 9),
('RCA Visys Integrated PBX 8-Line Router', 8),
('GBC VeloBind Cover Sets', 9),
('Colored Push Pins', 14),
('Logitech G105 Gaming Keyboard', 12),
('Xerox 1925', 11),
('QVS USB Car Charger 2-Port 2.1Amp for iPod/iPhone/iPad/iPad 2/iPad 3', 8),
('DAX Natural Wood-Tone Poster Frame', 6),
('StarTech.com 10/100 VDSL2 Ethernet Extender Kit', 16),
('Acco Smartsocket Table Surge Protector, 6 Color-Coded Adapter Outlets', 10),
('GBC ProClick Spines for 32-Hole Punch', 9),
('Memorex Mini Travel Drive 4 GB USB 2.0 Flash Drive', 12),
('Memorex Micro Travel Drive 16 GB', 12),
('Avery 497', 3),
('Staples', 14),
('Avery 500', 3),
('"While you Were Out" Message Book, One Form per Page', 11),
('Rediform Voice Mail Log Books', 11),
('OSullivan Manor Hill 2-Door Library in Brianna Oak', 1),
('Nu-Dell Float Frame 11 x 14 1/2', 6),
('Logitech G600 MMO Gaming Mouse', 12),
('Sauder Facets Collection Library, Sky Alder Finish', 1),
('Avanti 4.4 Cu. Ft. Refrigerator', 10),
('Hoover Replacement Belt for Commercial Guardsman Heavy-Duty Upright Vacuum', 10),
('Fellowes Advanced 8 Outlet Surge Suppressor with Phone/Fax Protection', 10),
('SAFCO PlanMaster Heigh-Adjustable Drafting Table Base, 43w x 30d x 30-37h, Black', 4),
('White GlueTop Scratch Pads', 11),
('Holmes HEPA Air Purifier', 10),
('TRENDnet 56K USB 2.0 Phone, Internet and Fax Modem', 12),
('Xerox 231', 11),
('Easy-staple paper', 11),
('Hon 2111 Invitation Series Straight Table', 4),
('Xerox 1962', 11),
('Wilson Electronics DB Pro Signal Booster', 8),
('Sauder Camden County Barrister Bookcase, Planked Cherry Finish', 1),
('DXL Angle-View Binders with Locking Rings, Black', 9),
('Sauder Camden County Collection Libraries, Planked Cherry Finish', 1),
('Advantus Panel Wall Certificate Holder - 8.5x11', 6),
('Avery 478', 3),
('Acco Data Flex Cable Posts For Top & Bottom Load Binders, 6" Capacity', 9),
('Recycled Steel Personal File for Standard File Folders', 5),
('Blackstonian Pencils', 7),
('Xerox 1919', 11),
('Tops Wirebound Message Log Books', 11),
('AT&T CL82213', 8),
('Maxell LTO Ultrium - 800 GB', 12),
('Office Star - Professional Matrix Back Chair with 2-to-1 Synchro Tilt and Mesh Fabric Seat', 2),
('Hunt BOSTON Vista Battery-Operated Pencil Sharpener, Black', 7),
('GE 30522EE2', 8),
('Ink Jet Note and Greeting Cards, 8-1/2" x 5-1/2" Card Size', 11),
('Logitech Wireless Marathon Mouse M705', 12),
('Mediabridge Sport Armband iPhone 5s', 8),
('DAX Cubicle Frames - 8x10', 6),
('Xerox 1929', 11),
('Avery 501', 3),
('Avery 513', 3),
('Harmony Air Purifier', 10),
('Electrix Incandescent Magnifying Lamp, Black', 6),
('Honeywell Enviracaire Portable Air Cleaner for up to 8 x 10 Room', 10),
('Global Stack Chair with Arms, Black', 2),
('Xerox 206', 11),
('Seth Thomas 14" Day/Date Wall Clock', 6),
('Samsung Galaxy S4 Mini', 8),
('Apple iPhone 5', 8),
('Polycom VVX 310 VoIP phone', 8),
('Bady BDG101FRU Card Printer', 16),
('Xerox 1998', 11),
('Honeywell Quietcare HEPA Air Cleaner', 10),
('Hon Olson Stacker Stools', 2),
('Dana Fluorescent Magnifying Lamp, White, 36"', 6),
('Flat Face Poster Frame', 6),
('Multi-Use Personal File Cart and Caster Set, Three Stacking Bins', 5),
('Xerox 1981', 11),
('Tops White Computer Printout Paper', 11),
('Staples in misc. colors', 7),
('Wilson Jones Elliptical Ring 3 1/2" Capacity Binders, 800 sheets', 9),
('Classic Ivory Antique Telephone ZL1810', 8),
('Sauder Forest Hills Library with Doors, Woodland Oak Finish', 1),
('Executive Impressions 8-1/2" Career Panel/Partition Cubicle Clock', 6),
('Jabra SPEAK 410 Multidevice Speakerphone', 8),
('Xerox 211', 11),
('Tennsco Industrial Shelving', 5),
('Newell 334', 7),
('Hon 30" x 60" Table with Locking Drawer', 4),
('Safco Drafting Table', 4),
('Staple envelope', 13),
('Avery 510', 3),
('Ultra Door Pull Handle', 6),
('Avery Hi-Liter Fluorescent Desk Style Markers', 7),
('IBM Multi-Purpose Copy Paper, 8 1/2 x 11", Case', 11),
('Newell 309', 7),
('GBC DocuBind TL300 Electric Binding System', 9),
('Jiffy Padded Mailers with Self-Seal Closure', 13),
('GBC DocuBind 200 Manual Binding Machine', 9),
('SKILCRAFT Telephone Shoulder Rest, 2" x 6.5" x 2.5", Black', 8),
('Global Comet Stacking Armless Chair', 2),
('Pressboard Hanging Data Binders for Unburst Sheets', 9),
('Hand-Finished Solid Wood Document Frame', 6),
('DAX Charcoal/Nickel-Tone Document Frame, 5 x 7', 6),
('Xerox 1891', 11),
('Hewlett-Packard Deskjet 5550 Printer', 16),
('Avery 474', 3),
('Panasonic KX T7736-B Digital phone', 8),
('GBC DocuBind TL200 Manual Binding Machine', 9),
('Global Commerce Series Low-Back Swivel/Tilt Chairs', 2),
('Staple magnet', 5),
('Cisco SPA 502G IP Phone', 8),
('Avaya 4621SW VoIP phone', 8),
('Xerox 214', 11),
('Motorola Moto X', 8),
('OSullivan 2-Shelf Heavy-Duty Bookcases', 1),
('Enermax Briskie RF Wireless Keyboard and Mouse Combo', 12),
('GBC Twin Loop Wire Binding Elements', 9),
('Perma STOR-ALL Hanging File Box, 13 1/8"W x 12 1/4"D x 10 1/2"H', 5),
('BIC Brite Liner Grip Highlighters', 7),
('WD My Passport Ultra 2TB Portable External Hard Drive', 12),
('Holmes Replacement Filter for HEPA Air Cleaner, Medium Room', 10),
('Imation Clip USB flash drive - 8 GB', 12),
('Newell 3-Hole Punched Plastic Slotted Magazine Holders for Binders', 9),
('Acco 6 Outlet Guardian Standard Surge Suppressor', 10),
('Acme Hot Forged Carbon Steel Scissors with Nickel-Plated Handles, 3 7/8" Cut, 8"L', 15),
('Avery Heavy-Duty EZD View Binder with Locking Rings', 9),
('Belkin Standard 104 key USB Keyboard', 12),
('Avaya IP Phone 1140E VoIP phone', 8),
('Global Wood Trimmed Managers Task Chair, Khaki', 2),
('Newell 321', 7),
('Jabra Supreme Plus Driver Edition Headset', 8),
('Binder Posts', 9),
('Bevis Round Conference Table Top & Single Column Base', 4),
('#10- 4 1/8" x 9 1/2" Recycled Envelopes', 13),
('Xerox 1978', 11),
('Eldon Spacemaker Box, Quick-Snap Lid, Clear', 7),
('Plymouth Boxed Rubber Bands by Plymouth', 14),
('3.6 Cubic Foot Counter Height Office Refrigerator', 10),
('OSullivan Elevations Bookcase, Cherry Finish', 1),
('Eldon ProFile File N Store Portable File Tub Letter/Legal Size Black', 5),
('Southworth Parchment Paper & Envelopes', 11),
('Tennsco Lockers, Sand', 5),
('Xerox 1922', 11),
('GBC Personal VeloBind Strips', 9),
('Novimex Fabric Task Chair', 2),
('Master Big Foot Doorstop, Beige', 6),
('Microsoft Wireless Mobile Mouse 4000', 12),
('Staples', 14),
('Letter/Legal File Tote with Clear Snap-On Lid, Black Granite', 5),
('Avery Framed View Binder, EZD Ring (Locking), Navy, 1 1/2"', 9),
('Xerox 1952', 11),
('Fellowes Twister Kit, Gray/Clear, 3/pkg', 9),
('Plantronics Audio 478 Stereo USB Headset', 12),
('Hon 94000 Series Round Tables', 4),
('Anker Ultra-Slim Mini Bluetooth 3.0 Wireless Keyboard', 12),
('Plantronics CS 50-USB - headset - Convertible, Monaural', 8),
('Computer Printout Paper with Letter-Trim Perforations', 11),
('Avery 52', 3),
('Translucent Push Pins by OIC', 14),
('Avery 507', 3),
('Newell 349', 7),
('GBC DocuBind P50 Personal Binding Machine', 9),
('Boston KS Multi-Size Manual Pencil Sharpener', 7),
('Tennsco 6- and 18-Compartment Lockers', 5),
('Xerox 1888', 11),
('Newell 308', 7),
('Polycom SoundStation2 EX Conference phone', 8),
('Mobile Personal File Cube', 5),
('DMI Eclipse Executive Suite Bookcases', 1),
('Quality Park Security Envelopes', 13),
('Belkin SportFit Armband For iPhone 5s/5c, Fuchsia', 8),
('DataProducts Ampli Magnifier Task Lamp, Black,', 6),
('Acco 6 Outlet Guardian Basic Surge Suppressor', 10),
('Sanford Colorific Scented Colored Pencils, 12/Pack', 7),
('Message Book, Phone, Wirebound Standard Line Memo, 2 3/4" X 5"', 11),
('Motorla HX550 Universal Bluetooth Headset', 8),
('Eldon Expressions Wood Desk Accessories, Oak', 6),
('Acme Office Executive Series Stainless Steel Trimmers', 15),
('Chromcraft Bull-Nose Wood 48" x 96" Rectangular Conference Tables', 4),
('Spigen Samsung Galaxy S5 Case Wallet', 8),
('Newell 33', 7),
('Panasonic KP-350BK Electric Pencil Sharpener with Auto Stop', 7),
('Array Memo Cubes', 11),
('Wilson Jones data.warehouse D-Ring Binders with DublLock', 9),
('Xerox 1982', 11),
('Hon Mobius Operators Chair', 2),
('Fellowes Mighty 8 Compact Surge Protector', 10),
('Harmony HEPA Quiet Air Purifiers', 10),
('Howard Miller 16" Diameter Gallery Wall Clock', 6),
('Eldon Executive Woodline II Desk Accessories, Mahogany', 6),
('Boston Model 1800 Electric Pencil Sharpener, Gray', 7),
('Polycom SoundPoint Pro SE-225 Corded phone', 8),
('Euro-Pro Shark Turbo Vacuum', 10),
('Metal Folding Chairs, Beige, 4/Carton', 2),
('Nontoxic Chalk', 7),
('Xerox 1991', 11),
('Atlantic Metals Mobile 2-Shelf Bookcases, Custom Colors', 1),
('Fellowes Advanced Computer Series Surge Protectors', 10),
('Recycled Steel Personal File for Hanging File Folders', 5),
('HTC One', 8),
('Manco Dry-Lighter Erasable Highlighter', 7),
('Fiskars Home & Office Scissors', 15),
('Eldon Cleatmat Chair Mats for Medium Pile Carpets', 6),
('Avery Self-Adhesive Photo Pockets for Polaroid Photos', 9),
('Xerox 1959', 11),
('Kensington 6 Outlet MasterPiece HOMEOFFICE Power Control Center', 10),
('Xerox 22', 11),
('Wi-Ex zBoost YX540 Cellular Phone Signal Booster', 8),
('Wirebound Message Books, Four 2 3/4" x 5" Forms per Page, 600 Sets per Book', 11),
('Logitech diNovo Edge Keyboard', 12),
('Xerox 1989', 11),
('Xerox 1984', 11),
('Xerox 227', 11),
('Fellowes Bases and Tops For Staxonsteel/High-Stak Systems', 5),
('Deflect-o Glass Clear Studded Chair Mats', 6),
('Canon PC1060 Personal Laser Copier', 17),
('Bevis Round Conference Room Tables and Bases', 4),
('Staple holder', 10),
('Xerox 1965', 11),
('Bionaire 99.97% HEPA Air Cleaner', 10),
('Eureka Sanitaire  Multi-Pro Heavy-Duty Upright, Disposable Bags', 10),
('Balt Solid Wood Round Tables', 4),
('Plantronics MX500i Earset', 8),
('Logitech G35 7.1-Channel Surround Sound Headset', 12),
('Imation Secure Drive + Hardware Encrypted USB flash drive - 16 GB', 12),
('Wausau Papers Astrobrights Colored Envelopes', 13),
('Tenex Antistatic Computer Chair Mats', 6),
('REDIFORM Incoming/Outgoing Call Register, 11" X 8 1/2", 100 Messages', 11),
('Tripp Lite Isotel 6 Outlet Surge Protector with Fax/Modem Protection', 10),
('Xerox 1994', 11),
('Nu-Dell Executive Frame', 6),
('Belkin 5 Outlet SurgeMaster Power Centers', 10),
('TOPS Carbonless Receipt Book, Four 2-3/4 x 7-1/4 Money Receipts per Page', 11),
('Insertable Tab Indexes For Data Binders', 9),
('Satellite Sectional Post Binders', 9),
('Memorex Micro Travel Drive 32 GB', 12),
('Lexmark S315 Color Inkjet Printer', 16),
('Xerox 1926', 11),
('Xerox 1918', 11),
('SpineVue Locking Slant-D Ring Binders by Cardinal', 9),
('Eureka The Boss Lite 10-Amp Upright Vacuum, Blue', 10),
('Global Leather & Oak Executive Chair, Burgundy', 2),
('Rubbermaid ClusterMat Chairmats, Mat Size- 66" x 60", Lip 20" x 11" -90 Degree Angle', 6),
('Dixon Ticonderoga Maple Cedar Pencil, #2', 7),
('Acco Hot Clips Clips to Go', 14),
('Acme Kleencut Forged Steel Scissors', 15),
('Xerox 1951', 11),
('DAX Solid Wood Frames', 6),
('Acco Smartsocket Color-Coded Six-Outlet AC Adapter Model Surge Protectors', 10),
('Staples in misc. colors', 7),
('Clearsounds A400', 8),
('Hewlett Packard 310 Color Digital Copier', 17),
('Staples', 14),
('Recycled Premium Regency Composition Covers', 9),
('Xerox 219', 11),
('Xerox 1903', 11),
('Logitech VX Revolution Cordless Laser Mouse for Notebooks (Black)', 12),
('OSullivan Plantations 2-Door Library in Landvery Oak', 1),
('Panasonic KX-TG9541B DECT 6.0 Digital 2-Line Expandable Cordless Phone With Digital Answering System', 8),
('Panasonic KX MB2061 Multifunction Printer', 16),
('Razer Kraken 7.1 Surround Sound Over Ear USB Gaming Headset', 12),
('Hon Rectangular Conference Tables', 4),
('Computer Printout Index Tabs', 9),
('GBC Wire Binding Combs', 9),
('Iceberg Nesting Folding Chair, 19w x 6d x 43h', 2),
('Honeywell Enviracaire Portable HEPA Air Cleaner for 16 x 20 Room', 10),
('Bevis Rectangular Conference Tables', 4),
('Ampad #10 Peel & Seel Holiday Envelopes', 13),
('Cardinal Holdit Data Disk Pockets', 9),
('Avery 496', 3),
('Black Print Carbonless Snap-Off Rapid Letter, 8 1/2" x 7"', 11),
('Xerox 23', 11),
('Eldon Pizzaz Desk Accessories', 6),
('Sauder Forest Hills Library, Woodland Oak Finish', 1),
('Global Deluxe High-Back Office Chair in Storm', 2),
('Kensington K72356US Mouse-in-a-Box USB Desktop Mouse', 12),
('Avery 50', 3),
('Fiskars Spring-Action Scissors', 15),
('Anker 24W Portable Micro USB Car Charger', 8),
('SAFCO Mobile Desk Side File, Wire Frame', 5),
('Newell 313', 7),
('Jawbone JAMBOX Wireless Bluetooth Speaker', 8),
('Xerox 1895', 11),
('#10 White Business Envelopes,4 1/8 x 9 1/2', 13),
('High Speed Automatic Electric Letter Opener', 15),
('Belkin 8 Outlet Surge Protector', 10),
('Panasonic KX TS3282B Corded phone', 8),
('Tennsco Snap-Together Open Shelving Units, Starter Sets and Add-On Units', 5),
('Avery 49', 3),
('Hoover Upright Vacuum With Dirt Cup', 10),
('Maxell 4.7GB DVD-RW 3/Pack', 12),
('Avery Non-Stick Binders', 9),
('Nortel Meridian M5316 Digital phone', 8),
('Bush Westfield Collection Bookcases, Dark Cherry Finish', 1),
('3M Polarizing Task Lamp with Clamp Arm, Light Gray', 6),
('HTC One Mini', 8),
('Dell Slim USB Multimedia Keyboard', 12),
('Contemporary Wood/Metal Frame', 6),
('OSullivan Living Dimensions 3-Shelf Bookcases', 1),
('KeyTronic KT800P2 - Keyboard - Black', 12),
('GBC Standard Plastic Binding Systems Combs', 9),
('Holmes Harmony HEPA Air Purifier for 17 x 20 Room', 10),
('GE General Use Halogen Bulbs, 100 Watts, 1 Bulb per Pack', 6),
('Macally Suction Cup Mount', 8),
('Eldon Image Series Black Desk Accessories', 6),
('Executive Impressions 14"', 6),
('Executive Impressions 12" Wall Clock', 6),
('Bretford CR8500 Series Meeting Room Furniture', 4),
('Plantronics Calisto P620-M USB Wireless Speakerphone System', 8),
('Hammermill CopyPlus Copy Paper (20Lb. and 84 Bright)', 11),
('Panasonic KX MC6040 Color Laser Multifunction Printer', 16),
('Berol Giant Pencil Sharpener', 7),
('KeyTronic KT400U2 - Keyboard - Black', 12),
('Avery 498', 3),
('Canon imageCLASS 2200 Advanced Copier', 17),
('Epson TM-T88V Direct Thermal Printer - Monochrome - Desktop', 16),
('Accohide Poly Flexible Ring Binders', 9),
('SAFCO Optional Arm Kit for Workspace Cribbage Stacking Chair', 2),
('Stackable Trays', 6),
('TOPS Voice Message Log Book, Flash Format', 11),
('Boston 1730 StandUp Electric Pencil Sharpener', 7),
('Executive Impressions 13" Clairmont Wall Clock', 6),
('GBC Laser Imprintable Binding System Covers, Desert Sand', 9),
('Xerox 2000', 11),
('Green Bar Computer Printout Paper', 11),
('Global Adaptabilites Bookcase, Cherry/Storm Gray Finish', 1),
('GBC Pre-Punched Binding Paper, Plastic, White, 8-1/2" x 11"', 9),
('Google Nexus 5', 8),
('Global Italian Leather Office Chair', 2),
('Advantus Motivational Note Cards', 11),
('Avery Flip-Chart Easel Binder, Black', 9),
('I.R.I.S IRISCard Anywhere 5 Card Scanner', 16),
('Ativa D5772 2-Line 5.8GHz Digital Expandable Corded/Cordless Phone System with Answering & Caller ID/Call Waiting, Black/Silver', 8),
('Ibico Presentation Index for Binding Systems', 9),
('Adams "While You Were Out" Message Pads', 11),
('Wirebound Four 2-3/4 x 5 Forms per Page, 400 Sets per Book', 11),
('AT&T 17929 Lendline Telephone', 8),
('Hewlett-Packard Deskjet 6540 Color Inkjet Printer', 16),
('Cisco TelePresence System EX90 Videoconferencing Unit', 16),
('Avery Fluorescent Highlighter Four-Color Set', 7),
('Xerox 1944', 11),
('Xerox 215', 11),
('Xerox 1885', 11),
('Computer Room Manger, 14"', 6),
('AT&T CL2909', 8),
('Plantronics Voyager Pro HD - Bluetooth Headset', 8),
('AT&T EL51110 DECT', 8),
('BlackBerry Q10', 8),
('Compact Automatic Electric Letter Opener', 15),
('SanDisk Ultra 16 GB MicroSDHC Class 10 Memory Card', 12),
('SanDisk Cruzer 8 GB USB Flash Drive', 12),
('Hon Deluxe Fabric Upholstered Stacking Chairs, Squared Back', 2),
('Advantus Rolling Drawer Organizers', 5),
('Maxell 4.7GB DVD-R 5/Pack', 12),
('GBC Plasticlear Binding Covers', 9),
('Plastic Stacking Crates & Casters', 5),
('Belkin F9M820V08 8 Outlet Surge', 10),
('APC 7 Outlet Network SurgeArrest Surge Protector', 10),
('Maxell 4.7GB DVD+R 5/Pack', 12),
('Anker Astro Mini 3000mAh Ultra-Compact Portable Charger', 8),
('Advantus Map Pennant Flags and Round Head Tacks', 14),
('Xerox 1953', 11),
('Xerox 228', 11),
('Advantus Employee of the Month Certificate Frame, 11 x 13-1/2', 6),
('Xerox 1954', 11),
('Embossed Ink Jet Note Cards', 11),
('Xerox 1942', 11),
('Carina Mini System Audio Rack, Model AR050B', 5),
('Xerox 201', 11),
('Eldon Expressions Punched Metal & Wood Desk Accessories, Black & Cherry', 6),
('GE 4 Foot Flourescent Tube, 40 Watt', 6),
('Nokia Lumia 925', 8),
('Staple remover', 15),
('Dana Swing-Arm Lamps', 6),
('Wirebound Message Books, Four 2 3/4 x 5 Forms per Page, 200 Sets per Book', 11),
('Xerox 1969', 11),
('Eldon 200 Class Desk Accessories, Smoke', 6),
('Dual Level, Single-Width Filing Carts', 5),
('Xerox 1971', 11),
('Staple envelope', 13),
('Boston 16750 Black Compact Battery Pencil Sharpener', 7),
('Eberhard Faber 3 1/2" Golf Pencils', 7),
('Tenex Carpeted, Granite-Look or Clear Contemporary Contour Shape Chair Mats', 6),
('Global Highback Leather Tilter in Burgundy', 2),
('Executive Impressions 13-1/2" Indoor/Outdoor Wall Clock', 6),
('Eldon 400 Class Desk Accessories, Black Carbon', 6),
('Wilson Jones Clip & Carry Folder Binder Tool for Ring Binders, Clear', 9),
('Harbour Creations 67200 Series Stacking Chairs', 2),
('Tenex V2T-RE Standard Weight Series Chair Mat, 45" x 53", Lip 25" x 12"', 6),
('Samsung Galaxy Mega 6.3', 8),
('DAX Two-Tone Rosewood/Black Document Frame, Desktop, 5 x 7', 6),
('Xerox 198', 11),
('Safco Chair Connectors, 6/Carton', 2),
('Xerox 1997', 11),
('Eldon Expressions Mahogany Wood Desk Collection', 6),
('VariCap6 Expandable Binder', 9),
('Stacking Trays by OIC', 6),
('Epson Perfection V600 Photo Scanner', 16),
('Durable Pressboard Binders', 9),
('Kensington 7 Outlet MasterPiece Power Center with Fax/Phone Line Protection', 10),
('Alliance Rubber Bands', 14),
('SlimView Poly Binder, 3/8"', 9),
('Boston Electric Pencil Sharpener, Model 1818, Charcoal Black', 7),
('DAX Clear Channel Poster Frame', 6),
('#10 Self-Seal White Envelopes', 13),
('Hon Pagoda Stacking Chairs', 2),
('Newell 339', 7),
('36X48 HARDFLOOR CHAIRMAT', 6),
('Anderson Hickey Conga Table Tops & Accessories', 4),
('Apple EarPods with Remote and Mic', 8),
('Perixx PERIBOARD-512B, Ergonomic Split Keyboard', 12),
('Logitech Wireless Headset H600 Over-The-Head Design', 12),
('Xerox 230', 11),
('Eldon Econocleat Chair Mats for Low Pile Carpets', 6),
('Vtech CS6719', 8),
('Xerox 194', 11),
('Bush Cubix Collection Bookcases, Fully Assembled', 1),
('Universal Recycled Hanging Pressboard Report Binders, Letter Size', 9),
('Xerox 1980', 11),
('Strathmore Photo Frame Cards', 11),
('Okidata C331dn Printer', 16),
('Seth Thomas 8 1/2" Cubicle Clock', 6),
('Aastra 6757i CT Wireless VoIP phone', 8),
('Xerox 1907', 11),
('G.E. Longer-Life Indoor Recessed Floodlight Bulbs', 6),
('Panasonic KX TS3282W Corded phone', 8),
('Global Leather and Oak Executive Chair, Black', 2),
('Cubify CubeX 3D Printer Double Head Print', 16),
('Ibico Ibimaster 300 Manual Binding System', 9),
('Wilson Jones Impact Binders', 9),
('Newell 34', 7),
('Polycom CX300 Desktop Phone USB VoIP phone', 8),
('Boston 1799 Powerhouse Electric Pencil Sharpener', 7),
('Staple envelope', 13),
('Wilson Jones Four-Pocket Poly Binders', 9),
('Sterilite Show Offs Storage Containers', 5),
('Alliance Super-Size Bands, Assorted Sizes', 14),
('BlueLounge Milo Smartphone Stand, White/Metallic', 8),
('Avery White Multi-Purpose Labels', 3),
('Logitech G500s Laser Gaming Mouse with Adjustable Weight Tuning', 12),
('Letter or Legal Size Expandable Poly String Tie Envelopes', 13),
('Stiletto Hand Letter Openers', 15),
('Tennsco Commercial Shelving', 5),
('Samsung HM1900 Bluetooth Headset', 8),
('Cisco SPA112 2 Port Phone Adapter', 8),
('Col-Erase Pencils with Erasers', 7),
('Xerox 221', 11),
('Plantronics Encore H101 Dual Earpieces Headset', 8),
('Disposable Triple-Filter Dust Bags', 10),
('Memorex Mini Travel Drive 64 GB USB 2.0 Flash Drive', 12),
('Fellowes Powershred HS-440 4-Sheet High Security Shredder', 16),
('Motorola Droid Maxx', 8),
('Xerox 1893', 11),
('Kensington Expert Mouse Optical USB Trackball for PC or Mac', 12),
('Master Caster Door Stop, Gray', 6),
('Tenex Chairmats For Use with Hard Floors', 6),
('Acco Flexible ACCOHIDE Square Ring Data Binder, Dark Blue, 11 1/2" X 14" 7/8"', 9),
('Fellowes Command Center 5-outlet power strip', 10),
('Rush Hierlooms Collection 1" Thick Stackable Bookcases', 1),
('Barricks 18" x 48" Non-Folding Utility Table with Bottom Storage Shelf', 4),
('Executive Impressions 10" Spectator Wall Clock', 6),
('Hon Metal Bookcases, Putty', 1),
('Tenex Personal Filing Tote With Secure Closure Lid, Black/Frost', 5),
('Xerox 1900', 11),
('OIC Stacking Trays', 6),
('Global Armless Task Chair, Royal Blue', 2),
('Eldon Executive Woodline II Cherry Finish Desk Accessories', 6),
('Message Book, Wirebound, Four 5 1/2" X 4" Forms/Pg., 200 Dupl. Sets/Book', 11),
('Tenex Traditional Chairmats for Hard Floors, Average Lip, 36" x 48"', 6),
('Polycom VoiceStation 500 Conference phone', 8),
('Binney & Smith inkTank Desk Highlighter, Chisel Tip, Yellow, 12/Box', 7),
('Speediset Carbonless Redi-Letter 7" x 8 1/2"', 11),
('Xerox 204', 11),
('KeyTronic E03601U1 - Keyboard - Beige', 12),
('Imation Bio 2GB USB Flash Drive Imation Corp', 12),
('Hon Metal Bookcases, Black', 1),
('Bush Birmingham Collection Bookcase, Dark Cherry', 1),
('AT&T 1080 Phone', 8),
('Avery Metallic Poly Binders', 9),
('Ativa MDM8000 8-Sheet Micro-Cut Shredder', 16),
('Acco 6 Outlet Guardian Premium Plus Surge Suppressor', 10),
('Smead Alpha-Z Color-Coded Name Labels First Letter Starter Set', 3),
('Ooma Telo VoIP Home Phone System', 8),
('Telephone Message Books with Fax/Mobile Section, 4 1/4" x 6"', 11),
('Xerox 200', 11),
('Okidata MB491 Multifunction Printer', 16),
('Staples in misc. colors', 7),
('Akro Stacking Bins', 5),
('Avery Hi-Liter Comfort Grip Fluorescent Highlighter, Yellow Ink', 7),
('Rosewill 107 Normal Keys USB Wired Standard Keyboard', 12),
('PayAnywhere Card Reader', 8),
('Xerox 1882', 11),
('Memorex 25GB 6X Branded Blu-Ray Recordable Disc, 30/Pack', 12),
('Boston Home & Office Model 2000 Electric Pencil Sharpeners', 7),
('Newell 31', 7),
('Premium Transparent Presentation Covers, No Pattern/Clear, 8 1/2" x 11"', 9),
('Xerox 1966', 11),
('Acme Kleen Earth Office Shears', 15),
('Maxell Pro 80 Minute CD-R, 10/Pack', 12),
('Imation Swivel Flash Drive USB flash drive - 8 GB', 12),
('Acrylic Self-Standing Desk Frames', 6),
('Elite 5" Scissors', 15),
('Acco Side-Punched Conventional Columnar Pads', 15),
('Avery 492', 3),
('Adjustable Personal File Tote', 5),
('Avery 05222 Permanent Self-Adhesive File Folder Labels for Typewriters, on Rolls, White, 250/Roll', 3),
('Prismacolor Color Pencil Set', 7),
('Sharp 1540cs Digital Laser Copier', 17),
('Eldon Regeneration Recycled Desk Accessories, Black', 6),
('Eldon File Chest Portable File', 5),
('Verbatim Slim CD and DVD Storage Cases, 50/Pack', 12),
('Letter Slitter', 15),
('Samsung Galaxy S4 Active', 8),
('Office Star - Mid Back Dual function Ergonomic High Back Chair with 2-Way Adjustable Arms', 2),
('Acco Bankers Clasps, 5 3/4"-Long', 14),
('Logitech Wireless Anywhere Mouse MX for PC and Mac', 12),
('Acco Economy Flexible Poly Round Ring Binder', 9),
('Balt Split Level Computer Training Table', 4),
('Dixon Ticonderoga Core-Lock Colored Pencils', 7),
('SAFCO Folding Chair Trolley', 2),
('Office Star - Contemporary Task Swivel chair with Loop Arms, Charcoal', 2),
('Avery 515', 3),
('TOPS 4 x 6 Fluorescent Color Memo Sheets, 500 Sheets per Pack', 11),
('Executive Impressions 13" Chairman Wall Clock', 6),
('Things To Do Today Spiral Book', 11),
('Logitech Illuminated Ultrathin Keyboard with Backlighting', 12),
('Serrated Blade or Curved Handle Hand Letter Openers', 15),
('Ibico EB-19 Dual Function Manual Binding System', 9),
('Eldon 300 Class Desk Accessories, Black', 6),
('Logitech G430 Surround Sound Gaming Headset with Dolby 7.1 Technology', 12),
('LG Exalt', 8),
('GBC Poly Designer Binding Covers', 9),
('Economy #2 Pencils', 7),
('Eldon "L" Workstation Diamond Chairmat', 6),
('DAX Copper Panel Document Frame, 5 x 7 Size', 6),
('Maxell 74 Minute CDR, 10/Pack', 12),
('Micro Innovations Wireless Classic Keyboard with Mouse', 12),
('Bush Heritage Pine Collection 5-Shelf Bookcase, Albany Pine Finish, *Special Order', 1),
('LG G3', 8),
('Riverleaf Stik-Withit Designer Note Cubes', 11),
('HP Office Paper (20Lb. and 87 Bright)', 11),
('Binney & Smith inkTank Erasable Pocket Highlighter, Chisel Tip, Yellow', 7),
('Staple envelope', 13),
('RCA ViSYS 25423RE1 Corded phone', 8),
('3M Polarizing Light Filter Sleeves', 6),
('Newell 348', 7),
('Xerox 1928', 11),
('Eldon Expressions Wood and Plastic Desk Accessories, Oak', 6),
('Black & Decker Filter for Double Action Dustbuster Cordless Vac BLDV7210', 10),
('Ultra Door Kickplate, 8"H x 34"W', 6),
('Boston 1900 Electric Pencil Sharpener', 7),
('WD My Passport Ultra 1TB Portable External Hard Drive', 12),
('Canon PC170 Desktop Personal Copier', 16),
('Memorex 25GB 6X Branded Blu-Ray Recordable Disc, 15/Pack', 12),
('Howard Miller 11-1/2" Diameter Brentwood Wall Clock', 6),
('Xerox 1890', 11),
('Jackery Bar Premium Fast-charging Portable Charger', 8),
('Permanent Self-Adhesive File Folder Labels for Typewriters, 1 1/8 x 3 1/2, White', 3),
('Prang Drawing Pencil Set', 7),
('Cisco IP Phone 7961G VoIP phone - Dark gray', 8),
('Hon Metal Bookcases, Gray', 1),
('Ibico EPK-21 Electric Binding System', 9),
('Holmes Visible Mist Ultrasonic Humidifier with 2.3-Gallon Output per Day, Replacement Filter', 10),
('Rush Hierlooms Collection Rich Wood Bookcases', 1),
('Kingston Digital DataTraveler 8GB USB 2.0', 12),
('HP Designjet T520 Inkjet Large Format Printer - 24" Color', 16),
('Newell 338', 7),
('Global Enterprise Series Seating High-Back Swivel/Tilt Chairs', 2),
('OSullivan 5-Shelf Heavy-Duty Bookcases', 1),
('Hammermill Color Copier Paper (28Lb. and 96 Bright)', 11),
('Xerox 1990', 11),
('Xerox 1933', 11),
('Green Canvas Binder for 8-1/2" x 14" Sheets', 9),
('Park Ridge Embossed Executive Business Envelopes', 13),
('Safco Value Mate Steel Bookcase, Baked Enamel Finish on Steel, Black', 1),
('Cisco Desktop Collaboration Experience DX650 IP Video Phone', 16),
('Howard Miller 12-3/4 Diameter Accuwave DS  Wall Clock', 6),
('Xerox 1975', 11),
('Newell 323', 7),
('Boston 1827 Commercial Additional Cutter, Drive Gear & Gear Rack for 1606', 7),
('Staple holder', 10),
('Mead 1st Gear 2" Zipper Binder, Asst. Colors', 9),
('3D Systems Cube Printer, 2nd Generation, Magenta', 16),
('Avery 487', 3),
('Hewlett-Packard Deskjet D4360 Printer', 16),
('DAX Wood Document Frame.', 6),
('Xerox 208', 11),
('Memorex Micro Travel Drive 4 GB', 12),
('#6 3/4 Gummed Flap White Envelopes', 13),
('DAX Two-Tone Silver Metal Document Frame', 6),
('Easy-staple paper', 11),
('Avery 503', 3),
('Holmes 99% HEPA Air Purifier', 10),
('OSullivan Cherrywood Estates Traditional Barrister Bookcase', 1),
('SANFORD Major Accent Highlighters', 7),
('Hon 4-Shelf Metal Bookcases', 1),
('Global Adaptabilities Conference Tables', 4),
('Newell 316', 7),
('Fellowes Staxonsteel Drawer Files', 5),
('Avery Hi-Liter Smear-Safe Highlighters', 7),
('Inter-Office Recycled Envelopes, Brown Kraft, Button-String,10" x 13" , 100/Box', 13),
('Xerox 1992', 11),
('Riverside Furniture Stanwyck Manor Table Series', 4),
('Fellowes Recycled Storage Drawers', 5),
('Xerox 190', 11),
('Xerox 1892', 11),
('Seidio BD2-HK3IPH5-BK DILEX Case and Holster Combo for Apple iPhone 5/5s - Black', 8),
('TOPS "Important Message" Pads, Canary, 4-1/4 x 5-1/2, 50 Sheets per Pad', 11),
('24 Capacity Maxi Data Binder Racks, Pearl', 5),
('Southworth 25% Cotton Premium Laser Paper and Envelopes', 11),
('Multimedia Mailers', 13),
('Avery 5', 3),
('Jensen SMPS-640 - speaker phone', 8),
('Master Caster Door Stop, Large Brown', 6),
('Fellowes Desktop Hanging File Manager', 5),
('Xerox 1956', 11),
('Nu-Dell Oak Frame', 6),
('GBC Therma-A-Bind 250T Electric Binding System', 9),
('Document Clip Frames', 6),
('Hoover Replacement Belts For Soft Guard & Commercial Ltweight Upright Vacs, 2/Pk', 10),
('Xerox 1937', 11),
('DAX Cubicle Frames, 8-1/2 x 11', 6),
('Sauder Camden County Collection Library', 1),
('Canon PC-428 Personal Copier', 17),
('Office Star - Ergonomic Mid Back Chair with 2-Way Adjustable Arms', 2),
('Xerox 1917', 11),
('SanDisk Cruzer 16 GB USB Flash Drive', 12),
('Imation 30456 USB Flash Drive 8GB', 12),
('Panasonic KX TS208W Corded phone', 8),
('Xerox 19', 11),
('SanDisk Cruzer 4 GB USB Flash Drive', 12),
('AmazonBasics 3-Button USB Wired Mouse', 12),
('14-7/8 x 11 Blue Bar Computer Printout Paper', 11),
('Tyvek Interoffice Envelopes, 9 1/2" x 12 1/2", 100/Box', 13),
('Kleencut Forged Office Shears by Acme United Corporation', 15),
('Avery Triangle Shaped Sheet Lifters, Black, 2/Pack', 9),
('Logitech Keyboard K120', 12),
('Xerox 1932', 11),
('Dixon Ticonderoga Pencils', 7),
('DAX Contemporary Wood Frame with Silver Metal Mat, Desktop, 11 x 14 Size', 6),
('Texas Instrument TI-15 Fraction Calculator', 16),
('Deflect-o EconoMat Nonstudded, No Bevel Mat', 6),
('OIC Thumb-Tacks', 14),
('Sanford EarthWrite Recycled Pencils, Medium Soft, #2', 7),
('PNY Rapid USB Car Charger - Black', 8),
('Hon Every-Day Chair Series Swivel Task Chairs', 2),
('SmartStand Mobile Device Holder, Assorted Colors', 8),
('Belkin 8-Outlet Premiere SurgeMaster II Surge Protectors', 10),
('Staples', 14),
('Euro Pro Shark Stick Mini Vacuum', 10),
('Easy-staple paper', 11),
('Astroparche Fine Business Paper', 11),
('Zebra ZM400 Thermal Label Printer', 16),
('Letter Size File', 5),
('Dexim XPower Skin Super-Thin Power Case for iPhone 5 - Black', 8),
('Samsung Galaxy S4', 8),
('Office Star Flex Back Scooter Chair with Aluminum Finish Frame', 2),
('Samsung Convoy 3', 8),
('Eldon Imàge Series Desk Accessories, Clear', 6),
('Avery 491', 3),
('Xerox 209', 11),
('Peel & Seel Recycled Catalog Envelopes, Brown', 13),
('Avanti 1.7 Cu. Ft. Refrigerator', 10),
('Acme Design Stainless Steel Bent Scissors', 15),
('Barricks Non-Folding Utility Table with Steel Legs, Laminate Tops', 4),
('Hewlett-Packard 300S Scientific Calculator', 16),
('Avery 495', 3),
('iOttie HLCRIO102 Car Mount', 8),
('Avery Hi-Liter GlideStik Fluorescent Highlighter, Yellow Ink', 7),
('Eldon 500 Class Desk Accessories', 6),
('EcoTones Memo Sheets', 11),
('Xerox 1906', 11),
('Texas Instruments TI-34 Scientific Calculator', 16),
('Standard Line “While You Were Out” Hardbound Telephone Message Book', 11),
('Kingston Digital DataTraveler 64GB USB 2.0', 12),
('GBC VeloBinder Strips', 9),
('Xerox 1963', 11),
('Logitech Z-906 Speaker sys - home theater - 5.1-CH', 12),
('Sanyo Counter Height Refrigerator with Crisper, 3.6 Cubic Foot, Stainless Steel/Black', 10),
('Luxo Adjustable Task Clamp Lamp', 6),
('Unpadded Memo Slips', 11),
('Barrel Sharpener', 7),
('Acco Glide Clips', 14),
('Bush Cubix Conference Tables, Fully Assembled', 4),
('Office Star - Contemporary Task Swivel chair with 2-way adjustable arms, Plum', 2),
('RCA H5401RE1 DECT 6.0 4-Line Cordless Handset With Caller ID/Call Waiting', 8),
('SAFCO PlanMaster Boards, 60w x 37-1/2d, White Melamine', 4),
('Xerox 20', 11),
('HP Officejet Pro 8600 e-All-In-One Printer, Copier, Scanner, Fax', 16),
('Black Print Carbonless 8 1/2" x 8 1/4" Rapid Memo Book', 11),
('Lunatik TT5L-002 Taktik Strike Impact Protection System for iPhone 5', 8),
('Iris 3-Drawer Stacking Bin, Black', 5),
('Panasonic Business Telephones KX-T7736', 8),
('Hunt Boston Vacuum Mount KS Pencil Sharpener', 7),
('Portfile Personal File Boxes', 5),
('Belkin 19" Center-Weighted Shelf, Gray', 5),
('Hon Comfortask Task/Swivel Chairs', 2),
('Career Cubicle Clock, 8 1/4", Black', 6),
('Peel & Seel Recycled Catalog Envelopes, Brown', 13),
('Boston 16765 Mini Stand Up Battery Pencil Sharpener', 7),
('Avery 475', 3),
('Vtech AT&T CL2940 Corded Speakerphone, Black', 16),
('Tenex B1-RE Series Chair Mats for Low Pile Carpets', 6),
('Griffin GC17055 Auxiliary Audio Cable', 8),
('Rogers Profile Extra Capacity Storage Tub', 5),
('RCA ViSYS 25825 Wireless digital phone', 8),
('Xerox 1914', 11),
('Xerox 1902', 11),
('Acme Titanium Bonded Scissors', 15),
('Ibico Recycled Linen-Style Covers', 9),
('Xerox 207', 11),
('Socket Bluetooth Cordless Hand Scanner (CHS)', 16),
('Okidata B400 Printer', 16),
('Logitech Wireless Boombox Speaker - portable - wireless, wired', 12),
('Xiaomi Mi3', 8),
('Xerox 1947', 11),
('Sony Micro Vault Click 4 GB USB 2.0 Flash Drive', 12),
('Xerox 193', 11),
('iOttie XL Car Mount', 8),
('Hoover Commercial Lightweight Upright Vacuum with E-Z Empty Dirt Cup', 10),
('First Data TMFD35 PIN Pad', 12),
('Ultra Commercial Grade Dual Valve Door Closer', 6),
('Contemporary Borderless Frame', 6),
('3D Systems Cube Printer, 2nd Generation, White', 16),
('Panasonic KX - TS880B Telephone', 8),
('Acco Recycled 2" Capacity Laser Printer Hanging Data Binders', 9),
('Xerox 1936', 11),
('Avery Legal 4-Ring Binder', 9),
('Avaya 5410 Digital phone', 8),
('TOPS Money Receipt Book, Consecutively Numbered in Red,', 11),
('Desktop 3-Pocket Hot File', 5),
('Wirebound Voice Message Log Book', 11),
('Konica Minolta magicolor 1690MF Multifunction Printer', 16),
('Linden 12" Wall Clock With Oak Frame', 6),
('Tensor Brushed Steel Torchiere Floor Lamp', 6),
('Ricoh - Ink Collector Unit for GX3000 Series Printers', 16),
('Wirebound Message Forms, Four 2 3/4 x 5 Forms per Page, Pink Paper', 11),
('Avery 479', 3),
('Okidata C610n Printer', 16),
('Xerox 229', 11),
('Acme Galleria Hot Forged Steel Scissors with Colored Handles', 15),
('Nu-Dell EZ-Mount Plastic Wall Frames', 6),
('Tensor Track Tree Floor Lamp', 6),
('Hon Olson Stacker Chairs', 2),
('Belkin 7-Outlet SurgeMaster Home Series', 10),
('Griffin GC36547 PowerJolt SE Lightning Charger', 8),
('Deflect-o DuraMat Antistatic Studded Beveled Mat for Medium Pile Carpeting', 6),
('Cherry 142-key Programmable Keyboard', 12),
('Motorola L703CM', 8),
('NeatDesk Desktop Scanner & Digital Filing System', 16),
('Hoover Commercial Lightweight Upright Vacuum', 10),
('Xerox 1976', 11),
('Stride Job 150 Highlighters, Chisel Tip, Assorted Colors', 7),
('Black Avery Memo-Size 3-Ring Binder, 5 1/2" x 8 1/2"', 9),
('Xerox 1983', 11),
('Tenex Chairmat w/ Average Lip, 45" x 53"', 6),
('Brother MFC-9340CDW LED All-In-One Printer, Copier Scanner', 16),
('Avery 484', 3),
('Electrix Fluorescent Magnifier Lamps & Weighted Base', 6),
('Okidata C610n Printer', 16),
('Space Solutions Industrial Galvanized Steel Shelving.', 5),
('Staples in misc. colors', 7),
('Plantronics Single Ear Headset', 16),
('Zebra GK420t Direct Thermal/Thermal Transfer Printer', 16),
('Tensor "Hersey Kiss" Styled Floor Lamp', 6),
('Memorex Mini Travel Drive 32 GB USB 2.0 Flash Drive', 12),
('Hoover Commercial SteamVac', 10),
('Xerox 1938', 11),
('NETGEAR RangeMax WNR1000 Wireless Router', 12),
('Xerox 1899', 11),
('Hewlett-Packard Desktjet 6988DT Refurbished Printer', 16),
('Bush Westfield Collection Bookcases, Dark Cherry Finish, Fully Assembled', 1),
('Executive Impressions 16-1/2" Circular Wall Clock', 6),
('Okidata MB760 Printer', 16),
('Dixon Ticonderoga Core-Lock Colored Pencils, 48-Color Set', 7),
('Executive Impressions 14" Contract Wall Clock with Quartz Movement', 6),
('Sterling Rubber Bands by Alliance', 14),
('Kensington 6 Outlet SmartSocket Surge Protector', 10),
('Maxell CD-R Discs', 12),
('Avery Hi-Liter Pen Style Six-Color Fluorescent Set', 7),
('Acme Design Line 8" Stainless Steel Bent Scissors w/Champagne Handles, 3-1/8" Cut', 15),
('Star Micronics TSP100 TSP143LAN Receipt Printer', 16),
('Xerox 1955', 11),
('Snap-A-Way Black Print Carbonless Speed Message, No Reply Area, Duplicate', 11),
('1/4 Fold Party Design Invitations & White Envelopes, 24 8-1/2" X 11" Cards, 25 Env./Pack', 11),
('Hewlett-Packard Deskjet F4180 All-in-One Color Ink-jet - Printer / copier / scanner', 16),
('Lexmark 20R1285 X6650 Wireless All-in-One Printer', 16),
('Nokia Lumia 1020', 8),
('Acme Serrated Blade Letter Opener', 15),
('Okidata B401 Printer', 16),
('Xerox Blank Computer Paper', 11),
('4009 Highlighters', 7),
('Global Enterprise Series Seating Low-Back Swivel/Tilt Chairs', 2),
('Self-Adhesive Address Labels for Typewriters with Dispenser Box', 3),
('Office Star - Task Chair with Contemporary Loop Arms', 2),
('Grip Seal Envelopes', 13),
('Penpower WorldCard Pro Card Scanner', 16),
('Sony 8GB Class 10 Micro SDHC R40 Memory Card', 12),
('RCA ViSYS 25425RE1 Corded phone', 8),
('Cisco 8961 IP Phone Charcoal', 16),
('Eureka Hand Vacuum, Bagless', 10),
('LG G2', 8),
