INSERT INTO subcategoria (titulo, id_categoria) VALUES 
('Estantes', 1),
('Cadeiras', 1),
('Etiquetas', 2),
('Tabelas', 1),
('Armazenar', 2),
('Mobiliário', 1),
('Arte', 2),
('Telefones', 3),
('Fichários', 2),
('Eletrodomésticos', 2),
('Papel', 2),
('Acessórios', 3),
('Envelopes', 2),
('Fechos', 2),
('Suprimentos', 2),
('Máquinas', 3),
('Copiadoras', 3),
